const EN = {
  "Benvenuto in": "Welcome to",
  "L’applicazione che ti insegna": "The app that teaches you",
  "i significati dei colori": "the meanings of colors",
  "Impara con Chroma": "Learn with Chroma",
  "Impara": "Learn",
  "Approfondisci la teoria": "Dive into the theory",
  "e la psicologia dei colori": "and psychology of color",
  "con lezioni interattive.": "with interactive lessons.",
  "Gioca e impara": "Play and learn",
  "Completa quiz, missioni": "Complete quizzes, missions",
  "e sfide per sbloccare": "and challenges to unlock",
  "nuovi colori e badge!": "new colors and badges!",
  "Inizia": "Start",
  "📲 Installa CHROMA per usarla a schermo intero": "📲 Install CHROMA to use it full screen",
  "Installa": "Install",
  "Ciao,": "Hi,",
  "Pronto a scoprire qualcosa di nuovo sui colori oggi?": "Ready to discover something new about colors today?",
  "Streak": "Streak",
  "Livello": "Level",
  "Sfida del giorno": "Daily challenge",
  "Missioni di oggi": "Today's missions",
  "Vai alle missioni": "Go to missions",
  "Colore del giorno": "Color of the day",
  "Apri ›": "Open ›",
  "Quest giornaliere": "Daily quests",
  "Fammi vedere cosa hai imparato sui colori": "Show me what you've learned about colors",
  "Verifica quello che hai imparato nelle ultime lezioni e scopri il tuo livello sulla psicologia dei colori": "Check what you've learned in the latest lessons and find out your level in color psychology",
  "I tuoi colori sbloccati": "Your unlocked colors",
  "Aiutaci a insegnare qualcosa di nuovo a Chroma!": "Help us teach Chroma something new!",
  "Il nostro modello di AI per la critica del colore": "Our AI model for color critique",
  "entra sul nostro sito": "visit our website",
  "Scopri": "Discover",
  "Strumenti": "Tools",
  "Laboratorio": "Lab",
  "Ruota dei colori, codici e armonie": "Color wheel, codes and harmonies",
  "Colori da una foto": "Colors from a photo",
  "Estrai e interpreta una palette": "Extract and interpret a palette",
  "Le mie palette": "My palettes",
  "Lezioni": "Lessons",
  "Quest": "Quests",
  "Vediamo cosa hai imparato sui colori": "Let's see what you've learned about colors",
  "Missioni attive": "Active missions",
  "Tutte le missioni ›": "All missions ›",
  "Percorso guidato": "Guided path",
  "Altre lezioni - Combinazioni di colori": "More lessons - Color combinations",
  "Dettaglio lezione": "Lesson",
  "Curiosità": "Did you know?",
  "Come funziona": "How it works",
  "Quando usarla": "When to use it",
  "Consulta la teoria": "Read the theory",
  "Profilo": "Profile",
  "Completamento di CHROMA": "CHROMA completion",
  "Colori sbloccati": "Colors",
  "Tempo totale": "Total time",
  "XP totali": "Total XP",
  "Ultimi 7 giorni": "Last 7 days",
  "Minuti": "Minutes",
  "I tuoi titoli": "Your titles",
  "titoli sbloccati · storico dei livelli": "titles unlocked · level history",
  "Condividi il tuo profilo": "Share your profile",
  "I tuoi progressi": "Your progress",
  "Quest completate": "Quests completed",
  "Badges": "Badges",
  "Le tue statistiche": "Your statistics",
  "Lezioni completate": "Lessons completed",
  "Quiz completati": "Quizzes completed",
  "Missioni completate": "Missions completed",
  "Giorni in streak": "Streak days",
  "Badge": "Badges",
  "Tutti": "All",
  "Ottenuti": "Earned",
  "Bloccati": "Locked",
  "Esplora": "Explore",
  "Palette personali": "Custom palettes",
  "＋ Crea una palette con i tuoi colori": "＋ Create a palette with your colors",
  "Condividi la palette": "Share the palette",
  "Missioni": "Missions",
  "Percorso": "Path",
  "Oggi": "Today",
  "Speciali": "Special",
  "Completa lezioni e quiz per ottenere XP e sbloccare nuovi colori.": "Complete lessons and quizzes to earn XP and unlock new colors.",
  "Si rinnovano ogni giorno e danno XP extra per salire di livello.": "They renew every day and give extra XP to level up.",
  "Torna ogni giorno: con la serie di giorni consecutivi sblocchi i colori speciali.": "Come back every day: a streak of consecutive days unlocks the special colors.",
  "Dettaglio missione": "Mission",
  "Progresso": "Progress",
  "Reward": "Reward",
  "Reward ottenuto": "Reward earned",
  "Reward ottenuto!": "Reward earned!",
  "Hai guadagnato:": "You earned:",
  "Ottimo!": "Great!",
  "Lezione completata": "Lesson completed",
  "Torna alle lezioni": "Back to lessons",
  "Quiz completato!": "Quiz completed!",
  "Risultato": "Result",
  "Risposte corrette": "Correct answers",
  "Accuratezza": "Accuracy",
  "Ricompense": "Rewards",
  "Nuovo badge!": "New badge!",
  "Rispondi correttamente a tutte le domande per sbloccare il colore!": "Answer every question correctly to unlock the color!",
  "Torna ai quiz": "Back to quizzes",
  "Quiz sui colori": "Color quizzes",
  "8 colori, dal rosso al nero · 8 quiz": "8 colors, from red to black · 8 quizzes",
  "Quiz sulle combinazioni dei colori": "Color combination quizzes",
  "Combinazione dei colori": "Color combinations",
  "Le basi delle combinazioni · Armonie di colore · 6 quiz": "Combination basics · Color harmonies · 6 quizzes",
  "Quiz sul colore digitale": "Digital color quizzes",
  "RGB, HEX, HSL, CMYK e contrasto · 5 quiz": "RGB, HEX, HSL, CMYK and contrast · 5 quizzes",
  "Allenamento dell'occhio": "Eye training",
  "Dal codice HEX al colore": "From HEX code to color",
  "Ordina per luminosità": "Sort by lightness",
  "Il colore opposto sulla ruota": "The opposite color on the wheel",
  "Fai 3 su 3 in un quiz per sbloccare un nuovo colore e usarlo come tema dell'app.": "Score 3 out of 3 in a quiz to unlock a new color and use it as the app theme.",
  "Combinazione colori": "Color combinations",
  "Tocca un colore sbloccato per usarlo come tema di tutta l'app.": "Tap an unlocked color to use it as the theme of the whole app.",
  "Tema attivo": "Active theme",
  "Ripristina": "Reset",
  "La tua tavolozza": "Your palette",
  "Nome": "Name",
  "Scegli fino a 6 colori": "Choose up to 6 colors",
  "Puoi usare solo i colori che hai sbloccato. Completa quiz e missioni per averne altri!": "You can only use the colors you've unlocked. Complete quizzes and missions to get more!",
  "Salva palette": "Save palette",
  "Impostazioni": "Settings",
  "Il tuo nome": "Your name",
  "Aspetto": "Appearance",
  "Automatico": "Automatic",
  "Chiaro": "Light",
  "Scuro": "Dark",
  "Colore del tema": "Theme color",
  "Lingua": "Language",
  "La lingua cambia da sola se scrivi il tuo nome con un altro alfabeto.": "The language changes automatically if you type your name in another alphabet.",
  "Installa l'app sul telefono": "Install the app on your phone",
  "Cerca aggiornamenti": "Check for updates",
  "Azzera tutti i progressi": "Reset all progress",
  "🧪 Modalità demo": "🧪 Demo mode",
  "Simula i progressi per provare o presentare l'app.": "Simulate progress to try out or present the app.",
  "+1 livello": "+1 level",
  "+1 giorno di streak": "+1 streak day",
  "Completa le lezioni": "Complete the lessons",
  "+5 quiz fatti": "+5 quizzes done",
  "Completa le missioni": "Complete the missions",
  "Sblocca tutti i badge": "Unlock all badges",
  "✨ Sblocca i colori segreti": "✨ Unlock the secret colors",
  "⭐ Simula utente esperto": "⭐ Simulate an expert user",
  "↺ Nuovo utente (azzera tutto)": "↺ New user (reset everything)",
  "Chiudi": "Close",
  "Conferma": "Confirm",
  "Immagine profilo": "Profile picture",
  "Carica una tua foto": "Upload your photo",
  "Oppure scegli un avatar": "Or choose an avatar",
  "Alcuni avatar si sbloccano salendo di livello.": "Some avatars unlock as you level up.",
  "Ogni livello ti dà un nuovo soprannome. Tocca un titolo ottenuto per mostrarlo nel profilo.": "Every level gives you a new nickname. Tap an earned title to show it on your profile.",
  "Hai completato CHROMA": "You completed CHROMA",
  "Colori segreti sbloccati!": "Secret colors unlocked!",
  "4 colorazioni animate, riservate a chi ha finito tutto il percorso.": "4 animated color themes, reserved for those who finished the whole path.",
  "Scoprili": "Discover them",
  "Più tardi": "Later",
  "Salva": "Save",
  "Nuovo titolo sbloccato": "New title unlocked",
  "Fantastico!": "Awesome!",
  "Tocca o trascina sulla ruota: il giro sceglie la tinta, la distanza dal centro la saturazione. La luminosità si regola qui sotto.": "Tap or drag on the wheel: the angle sets the hue, the distance from the center sets the saturation. Adjust the lightness below.",
  "Copia": "Copy",
  "Somiglia a": "Closest to",
  "Emozioni": "Emotions",
  "Armonie": "Harmonies",
  "Nessuna": "None",
  "Split": "Split",
  "Come lo vede chi è daltonico": "How people with color blindness see it",
  "Vista normale": "Normal vision",
  "Protanopia": "Protanopia",
  "Deuteranopia": "Deuteranopia",
  "Tritanopia": "Tritanopia",
  "Salva come palette": "Save as palette",
  "Scatta o scegli una foto: CHROMA ne estrae i colori principali, li misura e prova a interpretarli. La foto resta sul tuo dispositivo.": "Take or choose a photo: CHROMA extracts its main colors, measures them and tries to interpret them. The photo stays on your device.",
  "Scatta una foto": "Take a photo",
  "Dalla galleria": "From gallery",
  "Prova con un esempio": "Try an example",
  "Riduce la foto": "Shrinks the photo",
  "L'immagine viene ridotta a pochi pixel per lavorare velocemente.": "The image is reduced to a few pixels so it can be processed quickly.",
  "Raggruppa i colori": "Groups the colors",
  "Un algoritmo (k-means) unisce i pixel simili in 5 colori principali.": "An algorithm (k-means) merges similar pixels into 5 main colors.",
  "Li interpreta": "Interprets them",
  "Misura temperatura, saturazione e luce e li collega ai significati delle lezioni.": "It measures temperature, saturation and light and links them to the meanings from the lessons.",
  "La palette": "The palette",
  "Le misure": "Measurements",
  "Interpretazione": "Interpretation",
  "È un'interpretazione algoritmica: collega i colori ai significati studiati nelle lezioni, ma il senso di un'immagine dipende sempre dal contesto.": "This is an algorithmic interpretation: it links colors to the meanings studied in the lessons, but what an image means always depends on its context.",
  "Analizza un'altra foto": "Analyze another photo",
  "Come ti chiami?": "What's your name?",
  "Vedi tutti": "See all",
  "Indietro": "Back",
  "Cambia immagine del profilo": "Change profile picture",
  "Es. La mia estate": "E.g. My summer",
  "Anteprima della card": "Card preview",
  "Arance": "Oranges",
  "Esempio blu": "Blue example",
  "Esempio viola": "Purple example",
  "Home": "Home",
  "Serie: {m}": "Streak: {m}",
  "Missione: {m}": "Mission: {m}",
  "Completa tutte le lezioni, i quiz e le missioni": "Complete all lessons, quizzes and missions",
  "Benvenuto": "friend",
  "Ospite": "Guest",
  "h": "h",
  "min": "min",
  "🏆 Livello massimo raggiunto: hai completato tutto CHROMA!": "🏆 Maximum level reached: you completed all of CHROMA!",
  "Completa tutto il percorso per diventare <b>{t}</b> ({c})": "Complete the whole path to become <b>{t}</b> ({c})",
  "Ancora <b>{xp}</b> XP per diventare <b>{t}</b>": "<b>{xp}</b> XP to go to become <b>{t}</b>",
  "✓ Completata": "✓ Completed",
  "Prima la teoria": "Theory first",
  "✓ Completato": "✓ Completed",
  "Colore da riscattare": "Color to claim",
  "Record {n}/3": "Best {n}/3",
  "{a} / {b} lette": "{a} / {b} read",
  "{a} / {b} completate": "{a} / {b} completed",
  "{a} / {b} completati": "{a} / {b} completed",
  "5 min · livello base": "5 min · beginner level",
  "Lezione completata!": "Lesson completed!",
  "Lezione ripassata!": "Lesson reviewed!",
  "Hai guadagnato": "You earned",
  "Gli XP di questa lezione li hai già ottenuti": "You already earned the XP for this lesson",
  "Rifai il quiz": "Retake the quiz",
  "Fai il quiz": "Take the quiz",
  "avanti": "next",
  "Quiz": "Quiz",
  "Quiz (elenco)": "Quizzes",
  "✓ Letta": "✓ Read",
  "Arriva in fondo alla lezione per sbloccare il quiz": "Reach the end of the lesson to unlock the quiz",
  "Prima studia la teoria: poi il quiz si sblocca": "Study the theory first: then the quiz unlocks",
  "Esatto!": "Correct!",
  "Non proprio… la risposta giusta è evidenziata.": "Not quite… the right answer is highlighted.",
  "XP già ottenuti": "XP already earned",
  "Già riscattato": "Already claimed",
  "Riscatta": "Claim",
  "Tema attivo ✓": "Active theme ✓",
  "Usa come tema": "Use as theme",
  "Tema “{n}” applicato": "“{n}” theme applied",
  "Riscattato ✓": "Claimed ✓",
  "Nuovo colore sbloccato: {n}": "New color unlocked: {n}",
  "Tema segreto “{n}” attivato": "Secret theme “{n}” activated",
  "Tema originale": "Original theme",
  "Tema {n}": "{n} theme",
  "Come si sblocca: {h}": "How to unlock: {h}",
  "Tema originale ripristinato": "Original theme restored",
  "Studia “{n}” e fai 3 su 3 nel quiz": "Study “{n}” and score 3 out of 3 in the quiz",
  "Fai 3 su 3 in questo quiz per sbloccarlo": "Score 3 out of 3 in this quiz to unlock it",
  "Continua a giocare per sbloccarlo": "Keep playing to unlock it",
  "Colori segreti": "Secret colors",
  "Raggiungi il livello {l} completando tutto CHROMA per sbloccare 4 colorazioni animate. Completamento: {p}%": "Reach level {l} by completing all of CHROMA to unlock 4 animated color themes. Completion: {p}%",
  "Attivo": "Active",
  "Solo XP": "XP only",
  "Completata! Tocca per riscattare": "Completed! Tap to claim",
  "Riscattata ✓": "Claimed ✓",
  "Hai completato le missioni di oggi!": "You completed today's missions!",
  "Missioni di oggi: {a} / {b} completate": "Today's missions: {a} / {b} completed",
  "Missione del percorso": "Path mission",
  "Missione giornaliera": "Daily mission",
  "Missione speciale": "Special mission",
  "Già riscattata": "Already claimed",
  "Riscatta reward": "Claim reward",
  "personale": "custom",
  "Opzioni": "Options",
  "Apri": "Open",
  "Crea una palette simile": "Create a similar palette",
  "{n} (mia)": "{n} (mine)",
  "Condividi": "Share",
  "Modifica": "Edit",
  "Usa il primo colore come tema": "Use the first color as theme",
  "Apri nel Laboratorio": "Open in the Lab",
  "Elimina": "Delete",
  "Eliminare la palette?": "Delete this palette?",
  "“{n}” verrà cancellata.": "“{n}” will be deleted.",
  "Palette eliminata": "Palette deleted",
  "Usa {n} come tema": "Use {n} as theme",
  "Apri {n} nel Laboratorio": "Open {n} in the Lab",
  "Creata da te con {n} colori. Tocca un colore sbloccato qui sopra per usarlo come tema dell'app, o un codice per aprirlo nel Laboratorio.": "Created by you with {n} colors. Tap an unlocked color above to use it as the app theme, or a code to open it in the Lab.",
  "Creata da te con {n} colori. Tocca un colore qui sopra per aprirlo nel Laboratorio e scoprirne i codici.": "Created by you with {n} colors. Tap a color above to open it in the Lab and see its codes.",
  "Modifica palette": "Edit palette",
  "Nuova palette": "New palette",
  "Massimo 6 colori per palette": "Up to 6 colors per palette",
  "Dai un nome alla palette": "Give the palette a name",
  "Scegli almeno 2 colori": "Choose at least 2 colors",
  "Palette aggiornata": "Palette updated",
  "Palette creata!": "Palette created!",
  "Annulla": "Cancel",
  "Nome salvato": "Name saved",
  "Azzerare tutto?": "Reset everything?",
  "XP, livelli, lezioni, colori, badge e palette torneranno a zero e ripartirà l'onboarding.": "XP, levels, lessons, colors, badges and palettes will be reset and the onboarding will start again.",
  "Titolo aggiornato": "Title updated",
  "Scegli il titolo da mostrare": "Choose the title to show",
  "Vedi tutti i titoli…": "See all titles…",
  "prima del registro": "before tracking began",
  "Livello {l}": "Level {l}",
  "Prossimo · mancano {xp} XP": "Next · {xp} XP to go",
  "In mostra": "Shown",
  "Ora mostri: {n}": "Now showing: {n}",
  "La tua foto": "Your photo",
  "Si sblocca al livello {l}": "Unlocks at level {l}",
  "Avatar aggiornato": "Avatar updated",
  "Foto del profilo aggiornata": "Profile photo updated",
  "Immagine non valida": "Invalid image",
  "quiz": "quizzes",
  "lezioni": "lessons",
  "{u} in 7 giorni": "{u} in 7 days",
  "media al giorno": "daily average",
  "giorni attivi": "active days",
  "Il tuo giorno migliore: <b>{d}</b> ({v} {u})": "Your best day: <b>{d}</b> ({v} {u})",
  "Il livello {l} si sblocca solo completando tutto": "Level {l} unlocks only when you complete everything",
  "+1 ora di studio": "+1 hour of study",
  "Streak: {n} giorni": "Streak: {n} days",
  "{n} lezioni completate (+{xp} XP)": "{n} lessons completed (+{xp} XP)",
  "Lezioni già tutte completate": "All lessons already completed",
  "+5 quiz completati": "+5 quizzes completed",
  "Tutte le missioni sono pronte da riscattare!": "All missions are ready to claim!",
  "Tutti i {n} colori sbloccati": "All {n} colors unlocked",
  "Tutti i badge sbloccati": "All badges unlocked",
  "Profilo da utente esperto caricato": "Expert user profile loaded",
  "Nuovo utente?": "New user?",
  "Tutti i progressi verranno azzerati e ripartirà l'onboarding.": "All progress will be reset and the onboarding will start again.",
  "Ancora {n}…": "{n} more…",
  "CHROMA è già installata": "CHROMA is already installed",
  "Installa CHROMA su iPhone": "Install CHROMA on iPhone",
  "Installa CHROMA": "Install CHROMA",
  "Apri questa pagina con <b>Safari</b>": "Open this page in <b>Safari</b>",
  "Tocca il tasto <b>Condividi</b> (il quadrato con la freccia ↑)": "Tap the <b>Share</b> button (the square with the arrow ↑)",
  "Scegli <b>Aggiungi a Home</b> e poi <b>Aggiungi</b>": "Choose <b>Add to Home Screen</b> and then <b>Add</b>",
  "Apri CHROMA dall'icona: sarà a schermo intero": "Open CHROMA from the icon: it will be full screen",
  "Apri il menu del browser <b>⋮</b>": "Open the browser menu <b>⋮</b>",
  "Scegli <b>Installa app</b> o <b>Aggiungi a schermata Home</b>": "Choose <b>Install app</b> or <b>Add to Home screen</b>",
  "Ho capito": "Got it",
  "È disponibile una nuova versione di CHROMA": "A new version of CHROMA is available",
  "Aggiorna ora": "Update now",
  "Aggiornamento in corso…": "Updating…",
  "Aggiornare l'app?": "Update the app?",
  "Scarico l'ultima versione di CHROMA. I tuoi progressi restano salvati.": "I'll download the latest version of CHROMA. Your progress stays saved.",
  "Tesi magistrale": "Master's thesis",
  "CHROMA aggiornata all'ultima versione ✨": "CHROMA updated to the latest version ✨",
  "Copiato: {v}": "Copied: {v}",
  "Solo testi grandi": "Large text only",
  "Poco leggibile ✗": "Hard to read ✗",
  "Palette di sfumature salvata": "Shades palette saved",
  "Armonia salvata in Le mie palette": "Harmony saved in My palettes",
  "Prevalgono i colori caldi ({p}), che di solito vengono associati a energia, calore e vicinanza.": "Warm colors dominate ({p}); they are usually associated with energy, warmth and closeness.",
  "Prevalgono i colori freddi ({p}), che di solito vengono associati a calma, distanza e riflessione.": "Cool colors dominate ({p}); they are usually associated with calm, distance and reflection.",
  "Prevalgono i toni neutri ({p}): l'immagine risulta sobria e i pochi colori accesi risaltano di più.": "Neutral tones dominate ({p}): the image looks restrained and the few bright colors stand out more.",
  "I colori sono molto saturi: l'effetto è vivace.": "The colors are highly saturated: the effect is vivid.",
  "La saturazione è media: i colori non sono né spenti né accesi.": "Saturation is medium: the colors are neither dull nor bright.",
  "I colori sono tenui e poco saturi.": "The colors are soft and not very saturated.",
  "L'immagine è luminosa.": "The image is bright.",
  "La luminosità è media.": "Lightness is medium.",
  "L'immagine è scura.": "The image is dark.",
  "Il colore principale è vicino al tono “{n}”, che nelle lezioni viene associato a {e}.": "The main color is close to “{n}”, which the lessons associate with {e}.",
  "principale": "main",
  "Temperatura": "Temperature",
  "Calda": "Warm",
  "Fredda": "Cool",
  "Equilibrata": "Balanced",
  "Saturazione": "Saturation",
  "Luminosità": "Lightness",
  "Contrasto interno": "Internal contrast",
  "Molto forte: luci e ombre ben separate.": "Very strong: lights and shadows are clearly separated.",
  "Buono: luci e ombre sono ben distinte.": "Good: lights and shadows are well distinguished.",
  "Medio: toni abbastanza ravvicinati.": "Medium: tones are fairly close.",
  "Basso: toni molto simili tra loro.": "Low: tones are very similar to each other.",
  "Neutra": "Neutral",
  "Pochi colori saturi: domina la luce più della tinta.": "Few saturated colors: light matters more than hue.",
  "Monocromatica / analoga": "Monochromatic / analogous",
  "Le tinte sono vicine sulla ruota: l'insieme risulta coerente.": "The hues are close on the wheel: the whole looks consistent.",
  "Con contrasto complementare": "With complementary contrast",
  "Ci sono tinte quasi opposte sulla ruota: l'immagine ha un forte contrasto di colore.": "Some hues are almost opposite on the wheel: the image has a strong color contrast.",
  "Varia": "Varied",
  "Le tinte sono distribuite sulla ruota senza uno schema preciso.": "The hues are spread around the wheel without a clear scheme.",
  "Non riesco a leggere questa immagine": "I can't read this image",
  "Dalla foto": "From photo",
  "Palette della foto salvata": "Photo palette saved",
  "Punti {n}": "Points {n}",
  "Non proprio: quello giusto è evidenziato.": "Not quite: the right one is highlighted.",
  "Ordine perfetto!": "Perfect order!",
  "Quasi: l'ordine giusto è {o} (posizioni da sinistra).": "Almost: the right order is {o} (positions from the left).",
  "Round {n} / 5": "Round {n} / 5",
  "Fine!": "Finished!",
  "Hai fatto {n} su 5.": "You scored {n} out of 5.",
  "Ottimo occhio!": "Great eye!",
  "Riprova per allenarti ancora.": "Try again to keep training.",
  "Record: {n} / 5": "Best: {n} / 5",
  "Rigioca": "Play again",
  "Record {n}/5": "Best {n}/5",
  "Da provare": "Not played yet",
  "Preparo la tua card…": "Preparing your card…",
  "{p}% di CHROMA completato": "{p}% of CHROMA completed",
  "giorni di fila": "days in a row",
  "di studio": "of study",
  "I miei colori · {a}/{b}": "My colors · {a}/{b}",
  "Il mio profilo CHROMA": "My CHROMA profile",
  "Palette creata con CHROMA": "Palette created with CHROMA",
  "Combinazioni di colori": "Color combinations",
  "Il colore nel digitale": "Digital color",
  "Psicologia del colore": "Color psychology",
  "Significato": "Meaning",
  "La tua palette": "Your palette",
  "Emozioni associate": "Associated emotions",
  "Colori": "Colors",
  "Indovina il colore": "Guess the color",
  "Quale colore corrisponde a questo codice HEX?": "Which color matches this HEX code?",
  "Trova il complementare": "Find the complementary",
  "Quale colore sta dalla parte opposta della ruota?": "Which color is on the opposite side of the wheel?",
  "Dal chiaro allo scuro": "From light to dark",
  "Tocca i colori dal più chiaro al più scuro.": "Tap the colors from lightest to darkest.",
  "Grigio perla": "Pearl gray",
  "Grigio ardesia": "Slate gray",
  "Rosso": "Red",
  "Quiz sul rosso": "Red quiz",
  "Arancione": "Orange",
  "Quiz sull'arancione": "Orange quiz",
  "Giallo": "Yellow",
  "Quiz sul giallo": "Yellow quiz",
  "Verde": "Green",
  "Quiz sul verde": "Green quiz",
  "Blu": "Blue",
  "Quiz sul blu": "Blue quiz",
  "Viola": "Purple",
  "Quiz sul viola": "Purple quiz",
  "Bianco": "White",
  "Quiz sul bianco": "White quiz",
  "Nero": "Black",
  "Quiz sul nero": "Black quiz",
  "Turchese": "Turquoise",
  "Quiz Complementari": "Complementary quiz",
  "Lime": "Lime",
  "Quiz Analoghi": "Analogous quiz",
  "Magenta": "Magenta",
  "Quiz Triade": "Triad quiz",
  "Corallo": "Coral",
  "Quiz Split compl.": "Split compl. quiz",
  "Oliva": "Olive",
  "Quiz Rettangolo": "Rectangle quiz",
  "Petrolio": "Petrol blue",
  "Quiz Quadrato": "Square quiz",
  "Carminio": "Carmine",
  "Rosa": "Pink",
  "Terracotta": "Terracotta",
  "Oro": "Gold",
  "Verde bosco": "Forest green",
  "Salvia": "Sage",
  "Menta": "Mint",
  "Azzurro": "Sky blue",
  "Blu notte": "Midnight blue",
  "Lavanda": "Lavender",
  "Prugna": "Plum",
  "Marrone": "Brown",
  "Verde neon": "Neon green",
  "Quiz RGB": "RGB quiz",
  "Fucsia": "Fuchsia",
  "Quiz HEX": "HEX quiz",
  "Oltremare": "Ultramarine",
  "Quiz HSL": "HSL quiz",
  "Ghiaccio": "Ice blue",
  "Quiz CMYK": "CMYK quiz",
  "Pesca": "Peach",
  "Quiz Contrasto": "Contrast quiz",
  "Crema": "Cream",
  "Lampone": "Raspberry",
  "Rossi": "Reds",
  "Arancioni e terre": "Oranges and earth tones",
  "Gialli": "Yellows",
  "Verdi-gialli": "Yellow-greens",
  "Verdi": "Greens",
  "Ciano": "Cyans",
  "Rosa e magenta": "Pinks and magentas",
  "Neutri": "Neutrals",
  "passione": "passion",
  "energia": "energy",
  "urgenza": "urgency",
  "entusiasmo": "enthusiasm",
  "calore": "warmth",
  "creatività": "creativity",
  "ottimismo": "optimism",
  "luce": "light",
  "curiosità": "curiosity",
  "freschezza": "freshness",
  "vitalità": "vitality",
  "crescita": "growth",
  "natura": "nature",
  "equilibrio": "balance",
  "calma": "calm",
  "chiarezza": "clarity",
  "tecnologia": "technology",
  "fiducia": "trust",
  "stabilità": "stability",
  "mistero": "mystery",
  "lusso": "luxury",
  "gioia": "joy",
  "romanticismo": "romance",
  "originalità": "originality",
  "eleganza": "elegance",
  "semplicità": "simplicity",
  "Apprendista": "Apprentice",
  "Curioso del colore": "Color enthusiast",
  "Esploratore del colore": "Color explorer",
  "Osservatore di sfumature": "Shade observer",
  "Pittore alle prime armi": "Beginner painter",
  "Mescolatore di tinte": "Hue mixer",
  "Cacciatore di contrasti": "Contrast hunter",
  "Pittore sfumato": "Sfumato painter",
  "Alchimista dei pigmenti": "Pigment alchemist",
  "Maestro del colore": "Color master",
  "Custode della ruota cromatica": "Keeper of the color wheel",
  "Architetto delle armonie": "Architect of harmonies",
  "Poeta della luce": "Poet of light",
  "Virtuoso della palette": "Palette virtuoso",
  "Visionario cromatico": "Chromatic visionary",
  "Signore delle tonalità": "Lord of tones",
  "Guru del colore": "Color guru",
  "Mago dello spettro": "Spectrum wizard",
  "Oracolo dei colori": "Color oracle",
  "Leggenda cromatica": "Chromatic legend",
  "Primi passi": "First steps",
  "Completa la tua prima lezione.": "Complete your first lesson.",
  "Vai alle lezioni": "Go to lessons",
  "A metà strada": "Halfway there",
  "Completa 4 lezioni.": "Complete 4 lessons.",
  "Studente dei colori": "Color student",
  "Completa tutte le 8 lezioni di psicologia del colore.": "Complete all 8 color psychology lessons.",
  "Primo 3 su 3": "First 3 out of 3",
  "Rispondi correttamente a tutte le domande di un quiz.": "Answer every question of a quiz correctly.",
  "Vai ai quiz": "Go to quizzes",
  "Esperto di psicologia": "Psychology expert",
  "Fai 3 su 3 in tutti gli 8 quiz sui colori.": "Score 3 out of 3 in all 8 color quizzes.",
  "Teorico delle armonie": "Harmony theorist",
  "Leggi la teoria di tutte le 6 combinazioni di colori, fino alla seconda pagina.": "Read the theory of all 6 color combinations, up to the second page.",
  "Vai alle combinazioni": "Go to combinations",
  "Armonia perfetta": "Perfect harmony",
  "Fai 3 su 3 in tutti i 6 quiz sulle combinazioni.": "Score 3 out of 3 in all 6 combination quizzes.",
  "Creativo": "Creative",
  "Crea la tua prima palette personale con i colori sbloccati.": "Create your first custom palette with your unlocked colors.",
  "Vai alle palette": "Go to palettes",
  "Grande collezione": "Big collection",
  "Sblocca 15 colori tra quiz e missioni.": "Unlock 15 colors through quizzes and missions.",
  "I tuoi colori": "Your colors",
  "Nativo digitale": "Digital native",
  "Completa le 5 lezioni del percorso “Il colore nel digitale”.": "Complete the 5 lessons of the “Digital color” path.",
  "Occhio digitale": "Digital eye",
  "Fai 3 su 3 in tutti i 5 quiz sul colore digitale.": "Score 3 out of 3 in all 5 digital color quizzes.",
  "Sperimentatore": "Experimenter",
  "Crea un'armonia nel Laboratorio e salvala come palette.": "Create a harmony in the Lab and save it as a palette.",
  "Apri il Laboratorio": "Open the Lab",
  "Detective del colore": "Color detective",
  "Analizza i colori di una tua foto con “Colori da una foto”.": "Analyze the colors of one of your photos with “Colors from a photo”.",
  "Analizza una foto": "Analyze a photo",
  "Occhio allenato": "Trained eye",
  "Fai almeno 4 su 5 in tutti e 3 i giochi dell'allenamento.": "Score at least 4 out of 5 in all 3 training games.",
  "Vai ai giochi": "Go to games",
  "2 giorni di fila": "2 days in a row",
  "Apri CHROMA per 2 giorni consecutivi. Colore speciale!": "Open CHROMA for 2 days in a row. Special color!",
  "Torna domani": "Come back tomorrow",
  "3 giorni di fila": "3 days in a row",
  "Apri CHROMA per 3 giorni consecutivi. Colore speciale!": "Open CHROMA for 3 days in a row. Special color!",
  "4 giorni di fila": "4 days in a row",
  "Apri CHROMA per 4 giorni consecutivi. Colore speciale!": "Open CHROMA for 4 days in a row. Special color!",
  "Completa o ripassa 1 lezione": "Complete or review 1 lesson",
  "Oggi completa una lezione nuova o ripassane una già fatta.": "Today, complete a new lesson or review one you've already done.",
  "Rispondi a 2 quiz": "Answer 2 quizzes",
  "Oggi completa due quiz qualsiasi, anche già fatti.": "Today, complete any two quizzes, even ones you've already done.",
  "Fai un quiz perfetto": "Get a perfect quiz",
  "Oggi rispondi correttamente a tutte le domande di un quiz.": "Today, answer every question of a quiz correctly.",
  "Studia 5 minuti": "Study for 5 minutes",
  "Resta nell'app a studiare almeno 5 minuti oggi.": "Spend at least 5 minutes studying in the app today.",
  "Studia ora": "Study now",
  "Badge dello studente": "Student badge",
  "Badge dello studioso": "Scholar badge",
  "Badge digitale": "Digital badge",
  "Badge sociale": "Social badge",
  "Color Explorer": "Color Explorer",
  "Raccogli 10 colori": "Collect 10 colors",
  "Completa le 8 lezioni di psicologia del colore": "Complete the 8 color psychology lessons",
  "3/3 in tutti gli 8 quiz di psicologia del colore": "3/3 in all 8 color psychology quizzes",
  "Raggiungi il livello 10": "Reach level 10",
  "Completa le lezioni sul digitale": "Complete the digital color lessons",
  "4/5 in tutti i giochi": "4/5 in all games",
  "Collezionista": "Collector",
  "Sblocca tutti i colori": "Unlock all colors",
  "Classico": "Classic",
  "Chroma": "Chroma",
  "Tavolozza": "Palette",
  "Pennello": "Brush",
  "Goccia": "Drop",
  "Prisma": "Prism",
  "Sole": "Sun",
  "Luna": "Moon",
  "Foglia": "Leaf",
  "Occhio": "Eye",
  "Corona": "Crown",
  "Arcobaleno": "Rainbow",
  "Colori caldi": "Warm colors",
  "I colori caldi comprendono principalmente le tonalità di rosso, arancione e giallo. Richiamano il sole e il fuoco e vengono associati a vitalità, entusiasmo e dinamismo.": "Warm colors are mainly shades of red, orange and yellow. They recall the sun and fire and are associated with vitality, enthusiasm and dynamism.",
  "Passione": "Passion",
  "Energia": "Energy",
  "Calore": "Warmth",
  "Entusiasmo": "Enthusiasm",
  "Urgenza": "Urgency",
  "Colori freddi": "Cool colors",
  "I colori freddi comprendono principalmente le tonalità di blu, verde e viola. Richiamano l'acqua, il cielo e la vegetazione e vengono associati a calma, equilibrio e serenità.": "Cool colors are mainly shades of blue, green and purple. They recall water, the sky and vegetation and are associated with calm, balance and serenity.",
  "Calma": "Calm",
  "Stabilità": "Stability",
  "Fiducia": "Trust",
  "Serenità": "Serenity",
  "Relax": "Relaxation",
  "Mezzitoni": "Muted tones",
  "Qui con “mezzitoni” intendiamo colori smorzati: tinte a cui è stato aggiunto del grigio, meno sature e più morbide dei colori puri. Accostati tra loro creano un effetto armonioso ed equilibrato.": "Here “muted tones” means toned-down colors: hues with some gray added, less saturated and softer than pure colors. Placed together, they create a harmonious and balanced effect.",
  "Equilibrio": "Balance",
  "Armonia": "Harmony",
  "Nel film “Grand Budapest Hotel” (2014) di Wes Anderson ogni epoca ha la sua palette: rosa e pastelli per gli anni Trenta, toni più spenti e freddi per gli anni Sessanta.": "In Wes Anderson's film “The Grand Budapest Hotel” (2014), each era has its own palette: pinks and pastels for the 1930s, duller and cooler tones for the 1960s.",
  "Tutto lo spettro in movimento": "The whole spectrum in motion",
  "Aurora boreale": "Northern lights",
  "Verdi e viola che danzano": "Dancing greens and purples",
  "Tramonto": "Sunset",
  "Dall'arancio al magenta": "From orange to magenta",
  "Olografico": "Holographic",
  "Riflessi iridescenti": "Iridescent reflections",
  "Protanopia: i rossi appaiono più scuri e si confondono con i verdi. Riguarda circa 1 uomo su 100. La simulazione è un'approssimazione.": "Protanopia: reds look darker and get confused with greens. It affects about 1 in 100 men. The simulation is an approximation.",
  "Deuteranopia: verdi e rossi si confondono. Le difficoltà rosso-verde sono la forma più comune: contando le forme lievi riguardano circa 6 uomini su 100. La simulazione è un'approssimazione.": "Deuteranopia: greens and reds get confused. Red-green difficulties are the most common form: including the mild forms, they affect about 6 in 100 men. The simulation is an approximation.",
  "Tritanopia: blu e gialli si confondono. È molto rara e riguarda allo stesso modo uomini e donne. La simulazione è un'approssimazione.": "Tritanopia: blues and yellows get confused. It is very rare and affects men and women equally. The simulation is an approximation.",
  "Colore": "Color",
  "Il significato del blu": "The meaning of blue",
  "Il blu è uno dei colori più apprezzati: in molti sondaggi internazionali risulta il preferito. È associato al cielo e all'acqua e, nella cultura occidentale, viene collegato a calma, fiducia e stabilità.": "Blue is one of the best-loved colors: in many international surveys it comes out as the favorite. It is associated with the sky and water and, in Western culture, linked to calm, trust and stability.",
  "Per questo è molto usato da banche, aziende tecnologiche e istituzioni, che vogliono comunicare professionalità e affidabilità.": "That's why it is widely used by banks, tech companies and institutions that want to convey professionalism and reliability.",
  "Le tonalità più chiare tendono a evocare tranquillità e serenità, mentre quelle più scure vengono associate ad autorevolezza ed eleganza.": "Lighter shades tend to evoke tranquility and serenity, while darker ones are associated with authority and elegance.",
  "Molti social network e aziende tecnologiche hanno un logo blu: è un colore che il pubblico associa facilmente a fiducia e sicurezza.": "Many social networks and tech companies have a blue logo: people easily associate this color with trust and security.",
  "Il significato dell’arancione": "The meaning of orange",
  "L'arancione si ottiene mescolando rosso e giallo e sulla ruota cromatica si trova tra questi due colori. È un colore caldo e molto luminoso.": "Orange is obtained by mixing red and yellow, and on the color wheel it sits between these two colors. It is a warm and very bright color.",
  "Nella psicologia del colore viene associato all'entusiasmo, alla creatività e all'ottimismo: richiama l'attenzione in modo meno aggressivo del rosso.": "In color psychology it is associated with enthusiasm, creativity and optimism: it draws attention in a less aggressive way than red.",
  "Nel design viene usato spesso per pulsanti e inviti all'azione, perché cattura lo sguardo e comunica un tono amichevole e informale.": "In design it is often used for buttons and calls to action, because it catches the eye and conveys a friendly, informal tone.",
  "Il nome del colore viene da quello del frutto. In inglese antico, prima che l'arancia fosse conosciuta, questa tinta si chiamava geoluhread, cioè “giallo-rosso”.": "The color is named after the fruit. In Old English, before oranges were known, this hue was called geoluhread, meaning “yellow-red”.",
  "Il significato del viola": "The meaning of purple",
  "Il viola si ottiene mescolando rosso e blu. Nell'antichità le tinture viola erano rarissime e costose, e per questo è stato a lungo considerato un colore prezioso.": "Purple is obtained by mixing red and blue. In ancient times purple dyes were extremely rare and expensive, so it was long considered a precious color.",
  "Nella cultura occidentale viene associato alla creatività, alla spiritualità e al mistero, ma anche al lusso e alla regalità.": "In Western culture it is associated with creativity, spirituality and mystery, but also with luxury and royalty.",
  "Le tonalità chiare come il lilla vengono percepite come delicate e romantiche, mentre quelle profonde richiamano ricchezza e ambizione.": "Light shades such as lilac are perceived as delicate and romantic, while deep ones recall wealth and ambition.",
  "Nell'antica Roma la porpora di Tiro si ricavava da migliaia di molluschi ed era costosissima: la toga interamente purpurea era riservata ai generali durante il trionfo e, più tardi, agli imperatori.": "In ancient Rome, Tyrian purple was extracted from thousands of sea snails and was extremely expensive: the all-purple toga was reserved for generals during their triumph and, later, for emperors.",
  "Il significato del rosso": "The meaning of red",
  "Il rosso è il colore visibile con la lunghezza d'onda più lunga ed è tra quelli che attirano più rapidamente lo sguardo. È legato al fuoco, al sangue e alla passione.": "Red is the visible color with the longest wavelength and is among those that catch the eye most quickly. It is linked to fire, blood and passion.",
  "Nella cultura occidentale viene associato a energia, urgenza e desiderio, ed è il colore più usato per segnalare pericoli e divieti.": "In Western culture it is associated with energy, urgency and desire, and it is the color most often used to signal danger and prohibition.",
  "Nel design si usa con misura, per avvisi, saldi e pulsanti importanti, perché in grandi quantità può risultare aggressivo.": "In design it is used sparingly, for warnings, sales and important buttons, because in large amounts it can feel aggressive.",
  "Molte catene di fast food hanno il rosso nel logo: è un colore che si nota subito e che viene spesso associato al cibo e all'energia.": "Many fast-food chains have red in their logo: it is a color that stands out immediately and is often associated with food and energy.",
  "Il significato del giallo": "The meaning of yellow",
  "Tra i colori puri, il giallo è quello che appare più luminoso: richiama il sole, la luce e l'estate e cattura facilmente lo sguardo.": "Among pure colors, yellow is the one that looks brightest: it recalls the sun, light and summer and easily catches the eye.",
  "Viene associato all'ottimismo, alla creatività e alla curiosità; usato su grandi superfici, però, può risultare abbagliante e stancare la vista.": "It is associated with optimism, creativity and curiosity; on large surfaces, however, it can be dazzling and tire the eyes.",
  "Abbinato al nero crea un contrasto molto forte, leggibile anche a distanza: per questo è usato nella segnaletica e negli avvisi di pericolo.": "Paired with black it creates a very strong contrast, readable even from a distance: that's why it is used for signage and hazard warnings.",
  "Dal 1967 i taxi autorizzati di New York devono essere gialli: un colore che si riconosce subito, anche nel traffico.": "Since 1967, licensed New York taxis have had to be yellow: a color that is recognized immediately, even in traffic.",
  "Il significato del verde": "The meaning of green",
  "Il verde è il colore della natura, della crescita e del rinnovamento. L'occhio umano è particolarmente sensibile alla luce verde-gialla, che percepisce come molto luminosa.": "Green is the color of nature, growth and renewal. The human eye is particularly sensitive to yellow-green light, which it perceives as very bright.",
  "Viene associato a equilibrio, salute e tranquillità ed è considerato un colore riposante.": "It is associated with balance, health and tranquility and is considered a restful color.",
  "Nel design indica spesso qualcosa di positivo o permesso, come un'operazione riuscita o un semaforo che dà il via libera.": "In design it often signals something positive or allowed, such as a successful operation or a traffic light giving the go-ahead.",
  "In Europa i cartelli delle uscite di emergenza sono verdi, perché il verde indica sicurezza e “via libera”. Negli Stati Uniti, invece, le scritte EXIT sono spesso rosse.": "In Europe, emergency exit signs are green because green signals safety and “go”. In the United States, however, EXIT signs are often red.",
  "Il significato del bianco": "The meaning of white",
  "La luce bianca contiene tutti i colori dello spettro visibile, come mostra un prisma. Nella cultura occidentale il bianco rappresenta purezza, pulizia e nuovi inizi.": "White light contains all the colors of the visible spectrum, as a prism shows. In Western culture white represents purity, cleanliness and new beginnings.",
  "Nel design è fondamentale come spazio vuoto: dà respiro ai contenuti e comunica ordine, semplicità ed eleganza.": "In design it is essential as empty space: it gives content room to breathe and conveys order, simplicity and elegance.",
  "Il suo significato cambia con la cultura: in diversi paesi asiatici, come Cina, Giappone e India, il bianco è tradizionalmente il colore del lutto.": "Its meaning changes with culture: in several Asian countries, such as China, Japan and India, white is traditionally the color of mourning.",
  "Molti marchi di tecnologia usano grandi spazi bianchi nei negozi e nelle confezioni per comunicare semplicità e qualità.": "Many tech brands use large white spaces in their stores and packaging to convey simplicity and quality.",
  "Il significato del nero": "The meaning of black",
  "Il nero corrisponde all'assenza di luce. Viene associato a forza, eleganza e mistero, ma anche a serietà e, in molte culture occidentali, al lutto.": "Black corresponds to the absence of light. It is associated with strength, elegance and mystery, but also with seriousness and, in many Western cultures, with mourning.",
  "Nella moda e nel lusso è il colore della raffinatezza: fa apparire gli oggetti più preziosi e senza tempo.": "In fashion and luxury it is the color of sophistication: it makes objects look more precious and timeless.",
  "Nel design dà contrasto e peso: il testo nero su fondo bianco ha il contrasto massimo possibile (21:1) ed è tra le combinazioni più leggibili.": "In design it adds contrast and weight: black text on a white background has the highest possible contrast (21:1) and is among the most readable combinations.",
  "Nel 1926 la rivista Vogue presentò il “piccolo abito nero” di Coco Chanel come un capo adatto a tutte le donne: un colore legato al lutto diventò un simbolo di eleganza.": "In 1926 Vogue presented Coco Chanel's “little black dress” as a garment for every woman: a color linked to mourning became a symbol of elegance.",
  "RGB: i colori della luce": "RGB: the colors of light",
  "Gli schermi creano i colori con la luce: ogni pixel è formato da tre piccole luci, rossa (Red), verde (Green) e blu (Blue). Per questo il modello si chiama RGB.": "Screens create colors with light: each pixel is made of three tiny lights, red, green and blue. That's why the model is called RGB.",
  "È un modello additivo: più luce aggiungi, più il colore si schiarisce. Rosso e verde danno il giallo, verde e blu il ciano, rosso e blu il magenta; tutte e tre al massimo danno il bianco.": "It is an additive model: the more light you add, the lighter the color becomes. Red and green make yellow, green and blue make cyan, red and blue make magenta; all three at full strength make white.",
  "Ogni canale va da 0 a 255: rgb(255, 0, 0) è il rosso puro, rgb(0, 0, 0) il nero e rgb(255, 255, 255) il bianco. In tutto si ottengono più di 16 milioni di colori.": "Each channel goes from 0 to 255: rgb(255, 0, 0) is pure red, rgb(0, 0, 0) is black and rgb(255, 255, 255) is white. In total you get more than 16 million colors.",
  "Se guardi uno schermo con una lente d'ingrandimento vedi i piccoli punti rossi, verdi e blu che, da lontano, l'occhio fonde in un unico colore.": "If you look at a screen through a magnifying glass you can see tiny red, green and blue dots that, from a distance, the eye blends into a single color.",
  "Il codice HEX": "The HEX code",
  "Il codice HEX è un modo compatto di scrivere un colore RGB: un cancelletto seguito da sei caratteri, come #FF7A00.": "A HEX code is a compact way to write an RGB color: a hash sign followed by six characters, such as #FF7A00.",
  "I sei caratteri sono tre coppie: la prima indica il rosso, la seconda il verde, la terza il blu. Ogni coppia va da 00 (niente) a FF (massimo), cioè da 0 a 255 in numerazione esadecimale.": "The six characters are three pairs: the first is red, the second green, the third blue. Each pair goes from 00 (none) to FF (maximum), that is, from 0 to 255 in hexadecimal.",
  "È il formato più usato nel web e nel design: basta copiarlo per avere esattamente lo stesso colore in un sito, in Figma o in un'app.": "It is the most widely used format on the web and in design: just copy it to get exactly the same color on a website, in Figma or in an app.",
  "Il sistema esadecimale usa 16 simboli: le cifre da 0 a 9 e le lettere da A a F. Così FF vale 15 × 16 + 15 = 255.": "The hexadecimal system uses 16 symbols: the digits 0 to 9 and the letters A to F. So FF equals 15 × 16 + 15 = 255.",
  "Tinta, saturazione e luminosità": "Hue, saturation and lightness",
  "Il modello HSL descrive i colori in un modo vicino a come li descriviamo a parole. La tinta (Hue) è la posizione sulla ruota cromatica, da 0° a 360°: il rosso è a 0°, il verde a 120°, il blu a 240°.": "The HSL model describes colors in a way close to how we describe them in words. Hue is the position on the color wheel, from 0° to 360°: red is at 0°, green at 120°, blue at 240°.",
  "La saturazione dice quanto il colore è intenso: al 100% è vivo, allo 0% diventa grigio. La luminosità va dal nero (0%) al bianco (100%), con il colore pieno al 50%.": "Saturation tells how intense the color is: at 100% it is vivid, at 0% it becomes gray. Lightness goes from black (0%) to white (100%), with the full color at 50%.",
  "HSL è comodo per creare palette: tenendo ferma la tinta e cambiando saturazione e luminosità ottieni tante sfumature armoniche dello stesso colore.": "HSL is handy for building palettes: by keeping the hue fixed and changing saturation and lightness you get many harmonious shades of the same color.",
  "Le armonie si calcolano sulla tinta: il complementare è a 180°, una triade a 120°. Attenzione: sulla ruota digitale (RGB e HSL) il complementare del blu è il giallo, mentre sulla ruota tradizionale dei pittori (rosso, giallo, blu), usata nelle lezioni sulle combinazioni, è l'arancione.": "Harmonies are calculated on hue: the complementary color is 180° away, a triad 120° apart. Note: on the digital wheel (RGB and HSL) the complement of blue is yellow, while on the traditional painters' wheel (red, yellow, blue), used in the combination lessons, it is orange.",
  "RGB e CMYK: schermo e stampa": "RGB and CMYK: screen and print",
  "Le stampanti non usano la luce ma gli inchiostri: ciano (Cyan), magenta, giallo (Yellow) e nero (Key). È il modello CMYK.": "Printers don't use light but inks: cyan, magenta, yellow and black (Key). This is the CMYK model.",
  "È un modello sottrattivo: ogni inchiostro assorbe una parte della luce, quindi più inchiostro aggiungi, più il colore si scurisce. Il nero si aggiunge a parte perché mescolando ciano, magenta e giallo si ottiene un marrone scuro, non un nero pieno.": "It is a subtractive model: each ink absorbs part of the light, so the more ink you add, the darker the color becomes. Black is added separately because mixing cyan, magenta and yellow gives a dark brown, not a solid black.",
  "Alcuni colori molto accesi dello schermo non si possono stampare: per questo un colore può apparire più spento su carta che sul monitor, e chi progetta per la stampa controlla i colori in CMYK già durante il lavoro.": "Some very bright screen colors cannot be printed: that's why a color can look duller on paper than on a monitor, and print designers check their colors in CMYK while they work.",
  "La K di CMYK viene da Key plate, la lastra “chiave” che nella stampa tipografica portava i dettagli in nero.": "The K in CMYK comes from Key plate, the “key” printing plate that carried the black details.",
  "Contrasto e accessibilità": "Contrast and accessibility",
  "Un testo è leggibile quando c'è abbastanza differenza di luminosità tra testo e sfondo. Questa differenza si misura con il rapporto di contrasto, da 1:1 (nessuna differenza) a 21:1 (nero su bianco).": "Text is readable when there is enough difference in luminance between text and background. This difference is measured by the contrast ratio, from 1:1 (no difference) to 21:1 (black on white).",
  "Le linee guida internazionali WCAG chiedono almeno 4,5:1 per il testo normale e 3:1 per i testi grandi e le icone: è il livello AA. Il livello AAA chiede 7:1.": "The international WCAG guidelines require at least 4.5:1 for normal text and 3:1 for large text and icons: this is level AA. Level AAA requires 7:1.",
  "Circa l'8% degli uomini e lo 0,5% delle donne di origine europea ha una forma di daltonismo: per questo non bisogna affidare un'informazione solo al colore, ma aggiungere anche testo, icone o forme.": "About 8% of men and 0.5% of women of European descent have some form of color blindness: that's why information should never rely on color alone, but also on text, icons or shapes.",
  "Anche CHROMA controlla il contrasto: quando scegli un tema, l'app corregge da sola i colori perché testi e pulsanti restino leggibili.": "CHROMA checks contrast too: when you choose a theme, the app adjusts the colors by itself so that text and buttons stay readable.",
  "Complementari": "Complementary",
  "I colori complementari sono posizionati uno di fronte all'altro nella ruota cromatica. Creano il contrasto di tinta più forte e attirano subito l'attenzione.": "Complementary colors sit opposite each other on the color wheel. They create the strongest hue contrast and grab attention immediately.",
  "La combinazione utilizza due colori opposti. Sulla ruota tradizionale dei pittori (rosso, giallo, blu) le coppie sono blu e arancione, rosso e verde, giallo e viola.": "The combination uses two opposite colors. On the traditional painters' wheel (red, yellow, blue) the pairs are blue and orange, red and green, yellow and purple.",
  "Ideale per evidenziare elementi importanti, creare energia visiva e ottenere composizioni dinamiche. Esempi: Blu + Arancione, Rosso + Verde, Viola + Giallo.": "Ideal for highlighting important elements, adding visual energy and creating dynamic compositions. Examples: Blue + Orange, Red + Green, Purple + Yellow.",
  "Questa combinazione è molto utilizzata nel cinema, nella pubblicità e nel design per evidenziare elementi importanti. Alcuni esempi famosi sono il blu con l'arancione oppure il rosso con il verde.": "This combination is widely used in film, advertising and design to highlight important elements. Famous examples are blue with orange or red with green.",
  "I colori complementari possono essere usati per creare immagini energiche e dinamiche, ma devono essere bilanciati per evitare un effetto troppo aggressivo.": "Complementary colors can create energetic and dynamic images, but they need to be balanced to avoid an overly aggressive effect.",
  "Analoghi": "Analogous",
  "I colori analoghi sono colori vicini tra loro sulla ruota cromatica. Generano armonia e continuità visiva.": "Analogous colors are colors close to each other on the color wheel. They create harmony and visual continuity.",
  "Si scelgono generalmente tre colori adiacenti che condividono caratteristiche simili.": "You usually choose three adjacent colors that share similar characteristics.",
  "Perfetta per creare ambienti rilassanti, design equilibrati e palette naturali. Esempi: Blu + Blu-verde + Verde, Rosso + Rosso-arancio + Arancione.": "Perfect for relaxing settings, balanced designs and natural palettes. Examples: Blue + Blue-green + Green, Red + Red-orange + Orange.",
  "Questa combinazione è molto utilizzata per paesaggi, interfacce rilassanti e composizioni che devono trasmettere equilibrio.": "This combination is widely used for landscapes, relaxing interfaces and compositions meant to convey balance.",
  "Poiché il contrasto è limitato, i colori analoghi aiutano a creare una sensazione di continuità e fluidità visiva.": "Since the contrast is limited, analogous colors help create a sense of continuity and visual flow.",
  "Triade": "Triad",
  "La combinazione triadica utilizza tre colori equidistanti sulla ruota cromatica.": "The triadic combination uses three colors evenly spaced on the color wheel.",
  "I colori formano un triangolo equilatero e mantengono un buon equilibrio tra contrasto e armonia.": "The colors form an equilateral triangle and keep a good balance between contrast and harmony.",
  "Ottima per progetti creativi, illustrazioni e interfacce vivaci ma bilanciate. Esempi: Rosso + Giallo + Blu.": "Great for creative projects, illustrations and lively but balanced interfaces. Example: Red + Yellow + Blue.",
  "Questo schema crea palette vivaci e bilanciate, mantenendo un buon equilibrio tra contrasto e armonia.": "This scheme creates lively and balanced palettes, keeping a good balance between contrast and harmony.",
  "Molti loghi e illustrazioni utilizzano combinazioni triadiche per ottenere design accattivanti senza risultare disordinati.": "Many logos and illustrations use triadic combinations to look striking without appearing messy.",
  "Split complementari": "Split complementary",
  "Questa combinazione parte da un colore principale e utilizza i due colori adiacenti al suo complementare.": "This combination starts from a main color and uses the two colors adjacent to its complement.",
  "Offre un contrasto elevato ma meno aggressivo rispetto ai complementari diretti.": "It offers high contrast, but less aggressive than direct complementary colors.",
  "Ideale per chi desidera creare tensione visiva mantenendo una maggiore armonia. Esempi: Blu con Giallo-Arancio e Rosso-Arancio.": "Ideal if you want visual tension while keeping more harmony. Example: Blue with Yellow-orange and Red-orange.",
  "Questo sistema mantiene un forte contrasto ma risulta più equilibrato rispetto ai complementari diretti.": "This scheme keeps a strong contrast but looks more balanced than direct complementary colors.",
  "È molto apprezzato nel design perché offre varietà cromatica senza creare tensioni visive eccessive.": "It is popular in design because it offers color variety without creating excessive visual tension.",
  "Rettangolo": "Rectangle",
  "La combinazione rettangolare utilizza quattro colori organizzati in due coppie complementari.": "The rectangular combination uses four colors arranged in two complementary pairs.",
  "I colori formano un rettangolo sulla ruota cromatica, offrendo una palette ricca e versatile.": "The colors form a rectangle on the color wheel, offering a rich and versatile palette.",
  "Perfetta per progetti complessi che richiedono varietà cromatica mantenendo equilibrio. Esempi: Blu, Verde, Arancione e Rosso.": "Perfect for complex projects that need color variety while staying balanced. Example: Blue, Green, Orange and Red.",
  "Questo schema offre molta varietà cromatica e permette di creare composizioni ricche e dinamiche.": "This scheme offers plenty of color variety and lets you create rich, dynamic compositions.",
  "Per ottenere un buon risultato è consigliabile scegliere un colore dominante e usare gli altri come supporto.": "For a good result it is best to choose one dominant color and use the others in support.",
  "Quadrato": "Square",
  "La combinazione quadrata utilizza quattro colori equidistanti tra loro sulla ruota cromatica.": "The square combination uses four colors evenly spaced on the color wheel.",
  "I colori formano un quadrato e distribuiscono uniformemente il contrasto.": "The colors form a square and distribute contrast evenly.",
  "Ideale per creare design energici, moderni e molto colorati. Esempio sulla ruota tradizionale: Giallo, Rosso-arancio, Viola e Blu-verde.": "Ideal for energetic, modern and very colorful designs. Example on the traditional wheel: Yellow, Red-orange, Purple and Blue-green.",
  "Produce palette molto vivaci e dinamiche grazie alla distribuzione uniforme dei colori.": "It produces very lively and dynamic palettes thanks to the even distribution of colors.",
  "È uno schema ideale per progetti creativi, illustrazioni e design che vogliono trasmettere energia e movimento.": "It is an ideal scheme for creative projects, illustrations and designs meant to convey energy and movement.",
  "A quali sensazioni viene associato più spesso il blu?": "Which feelings is blue most often associated with?",
  "A) Calma e fiducia": "A) Calm and trust",
  "B) Rabbia e urgenza": "B) Anger and urgency",
  "C) Fame ed energia": "C) Hunger and energy",
  "Perché molte aziende tecnologiche usano il blu?": "Why do many tech companies use blue?",
  "A) Perché è economico da stampare": "A) Because it's cheap to print",
  "B) Perché viene associato all'affidabilità": "B) Because it is associated with reliability",
  "C) Perché attira l'attenzione sui saldi": "C) Because it draws attention to sales",
  "A cosa vengono associate le tonalità scure del blu?": "What are dark shades of blue associated with?",
  "A) Allegria e gioco": "A) Fun and play",
  "B) Pericolo": "B) Danger",
  "C) Autorevolezza ed eleganza": "C) Authority and elegance",
  "Da quali colori nasce l'arancione?": "Which colors make orange?",
  "A) Rosso e Giallo": "A) Red and yellow",
  "B) Blu e Giallo": "B) Blue and yellow",
  "C) Rosso e Blu": "C) Red and blue",
  "Quale emozione viene associata all'arancione?": "Which emotion is associated with orange?",
  "A) Tristezza": "A) Sadness",
  "B) Entusiasmo": "B) Enthusiasm",
  "C) Freddezza": "C) Coldness",
  "Dove viene usato spesso l'arancione nel design?": "Where is orange often used in design?",
  "A) Negli sfondi dei documenti legali": "A) In the background of legal documents",
  "B) Nei testi lunghi": "B) In long texts",
  "C) Nei pulsanti di invito all'azione": "C) In call-to-action buttons",
  "Da quali colori nasce il viola?": "Which colors make purple?",
  "A) Giallo e Blu": "A) Yellow and blue",
  "B) Rosso e Blu": "B) Red and blue",
  "C) Verde e Rosso": "C) Green and red",
  "A cosa è storicamente associato il viola?": "What has purple historically been associated with?",
  "A) Alla regalità e al lusso": "A) Royalty and luxury",
  "B) Al lavoro nei campi": "B) Farm work",
  "C) Alla segnaletica stradale": "C) Road signs",
  "Come vengono percepite spesso le tonalità chiare come il lilla?": "How are light shades such as lilac often perceived?",
  "A) Pericolo": "A) Danger",
  "B) Aggressività": "B) Aggressiveness",
  "C) Delicatezza e romanticismo": "C) Delicacy and romance",
  "Quali sensazioni vengono associate al rosso?": "Which feelings are associated with red?",
  "A) Energia e urgenza": "A) Energy and urgency",
  "B) Calma e riposo": "B) Calm and rest",
  "Perché il rosso va usato con misura nel design?": "Why should red be used sparingly in design?",
  "A) Perché è poco visibile": "A) Because it's hard to see",
  "B) Perché può risultare aggressivo": "B) Because it can feel aggressive",
  "C) Perché non si stampa bene": "C) Because it doesn't print well",
  "Dove si usa spesso il rosso?": "Where is red often used?",
  "A) Negli sfondi dei testi lunghi": "A) In the background of long texts",
  "B) Nelle app per dormire": "B) In sleep apps",
  "C) In avvisi, saldi e pulsanti importanti": "C) In warnings, sales and important buttons",
  "A cosa viene associato il giallo?": "What is yellow associated with?",
  "A) Al lutto": "A) Mourning",
  "B) All'ottimismo e alla luce": "B) Optimism and light",
  "C) Al silenzio": "C) Silence",
  "Con quale colore il giallo è più leggibile a distanza?": "With which color is yellow most readable from a distance?",
  "A) Con il nero": "A) With black",
  "B) Con il bianco": "B) With white",
  "C) Con l'arancione": "C) With orange",
  "Cosa può succedere usando troppo giallo?": "What can happen if you use too much yellow?",
  "A) Il testo diventa più leggibile": "A) Text becomes more readable",
  "B) Scompare il contrasto con il nero": "B) The contrast with black disappears",
  "C) Può abbagliare e stancare la vista": "C) It can dazzle and tire the eyes",
  "Quale concetto viene associato al verde?": "Which concept is associated with green?",
  "B) Lusso": "B) Luxury",
  "C) Natura e crescita": "C) Nature and growth",
  "Cosa indica il verde nelle interfacce?": "What does green indicate in interfaces?",
  "A) Un'operazione riuscita": "A) A successful operation",
  "B) Un errore grave": "B) A serious error",
  "C) Un contenuto vietato": "C) Forbidden content",
  "Che effetto viene attribuito al verde?": "Which effect is attributed to green?",
  "A) Agitazione": "A) Agitation",
  "B) Equilibrio e riposo": "B) Balance and rest",
  "C) Fame": "C) Hunger",
  "Cosa contiene la luce bianca?": "What does white light contain?",
  "A) Nessun colore": "A) No colors",
  "B) Tutti i colori dello spettro visibile": "B) All the colors of the visible spectrum",
  "C) Solo il blu": "C) Only blue",
  "A cosa serve il bianco nel design?": "What is white used for in design?",
  "A) A dare respiro ai contenuti": "A) To give content room to breathe",
  "B) A nascondere il testo": "B) To hide text",
  "C) Ad aumentare il caos": "C) To add chaos",
  "In diversi paesi asiatici il bianco rappresenta tradizionalmente…": "In several Asian countries, white traditionally represents…",
  "A) La festa": "A) Celebration",
  "B) La ricchezza": "B) Wealth",
  "C) Il lutto": "C) Mourning",
  "Il nero è…": "Black is…",
  "A) L'assenza di luce": "A) The absence of light",
  "B) La somma di tutti i colori della luce": "B) The sum of all the colors of light",
  "C) Un colore caldo": "C) A warm color",
  "In quale settore il nero viene associato alla raffinatezza?": "In which field is black associated with sophistication?",
  "A) Nei giochi per bambini": "A) Children's games",
  "B) Nella moda e nel lusso": "B) Fashion and luxury",
  "C) Nella segnaletica stradale": "C) Road signs",
  "Quale di queste combinazioni è la più leggibile?": "Which of these combinations is the most readable?",
  "A) Giallo su bianco": "A) Yellow on white",
  "B) Blu su viola": "B) Blue on purple",
  "C) Testo nero su fondo bianco": "C) Black text on a white background",
  "Che cosa significa RGB?": "What does RGB stand for?",
  "A) Rosso, Giallo, Blu": "A) Red, Yellow, Blue",
  "B) Red, Green, Blue: rosso, verde, blu": "B) Red, Green, Blue",
  "C) Rosa, Grigio, Bianco": "C) Pink, Gray, White",
  "Cosa ottieni sommando luce rossa e luce verde?": "What do you get by adding red light and green light?",
  "A) Giallo": "A) Yellow",
  "B) Marrone": "B) Brown",
  "C) Viola": "C) Purple",
  "Quale valore rappresenta il bianco?": "Which value represents white?",
  "Quale di questi è un codice HEX valido?": "Which of these is a valid HEX code?",
  "Nel codice #FF0000, quale canale è al massimo?": "In the code #FF0000, which channel is at its maximum?",
  "A) Il verde": "A) Green",
  "B) Il rosso": "B) Red",
  "C) Il blu": "C) Blue",
  "Che colore è #000000?": "What color is #000000?",
  "A) Bianco": "A) White",
  "B) Grigio": "B) Gray",
  "C) Nero": "C) Black",
  "Cosa indica la tinta (Hue)?": "What does hue indicate?",
  "A) La posizione del colore sulla ruota": "A) The color's position on the wheel",
  "B) Quanto il colore è chiaro": "B) How light the color is",
  "C) Quanto costa stamparlo": "C) How much it costs to print",
  "Un colore con saturazione 0% appare…": "A color with 0% saturation looks…",
  "A) Più vivo": "A) More vivid",
  "C) Fluorescente": "C) Fluorescent",
  "A quanti gradi di distanza si trova il complementare?": "How many degrees away is the complementary color?",
  "Quale modello usano le stampanti?": "Which model do printers use?",
  "Nel modello sottrattivo, aggiungendo inchiostro il colore diventa…": "In the subtractive model, adding ink makes the color…",
  "A) Più chiaro": "A) Lighter",
  "B) Più scuro": "B) Darker",
  "C) Trasparente": "C) Transparent",
  "Perché un colore acceso può sembrare spento su carta?": "Why can a bright color look dull on paper?",
  "A) Perché la carta è bianca": "A) Because paper is white",
  "B) Perché lo schermo è rotto": "B) Because the screen is broken",
  "C) Perché alcuni colori RGB non sono stampabili in CMYK": "C) Because some RGB colors can't be printed in CMYK",
  "Qual è il contrasto minimo AA per un testo normale?": "What is the minimum AA contrast for normal text?",
  "Quale combinazione ha il contrasto più alto?": "Which combination has the highest contrast?",
  "A) Nero su bianco": "A) Black on white",
  "B) Giallo su bianco": "B) Yellow on white",
  "C) Grigio su grigio": "C) Gray on gray",
  "Come aiuti chi è daltonico?": "How can you help people with color blindness?",
  "A) Usando solo rosso e verde": "A) By using only red and green",
  "B) Usando colori più chiari": "B) By using lighter colors",
  "C) Affiancando al colore testo, icone o forme": "C) By adding text, icons or shapes to color",
  "Dove si trovano i colori complementari sulla ruota cromatica?": "Where are complementary colors on the color wheel?",
  "A) Uno accanto all'altro": "A) Next to each other",
  "B) Uno di fronte all'altro": "B) Opposite each other",
  "C) A 90° uno dall'altro": "C) 90° apart",
  "Quale di queste è una coppia complementare?": "Which of these is a complementary pair?",
  "A) Blu e Arancione": "A) Blue and orange",
  "B) Blu e Azzurro": "B) Blue and sky blue",
  "C) Rosso e Arancione": "C) Red and orange",
  "A cosa bisogna fare attenzione usando i complementari?": "What should you watch out for when using complementary colors?",
  "A) Sono troppo spenti": "A) They are too dull",
  "B) Non si notano": "B) They go unnoticed",
  "C) Vanno bilanciati per non risultare aggressivi": "C) They need balancing so they don't feel aggressive",
  "Come sono disposti i colori analoghi?": "How are analogous colors arranged?",
  "A) Vicini tra loro sulla ruota": "A) Close together on the wheel",
  "B) Opposti tra loro": "B) Opposite each other",
  "C) Ai vertici di un quadrato": "C) At the corners of a square",
  "Quale palette è analoga?": "Which palette is analogous?",
  "A) Rosso + Verde": "A) Red + Green",
  "B) Blu + Blu-verde + Verde": "B) Blue + Blue-green + Green",
  "C) Giallo + Viola": "C) Yellow + Purple",
  "Che effetto producono di solito i colori analoghi?": "What effect do analogous colors usually create?",
  "A) Tensione e conflitto": "A) Tension and conflict",
  "B) Massimo contrasto": "B) Maximum contrast",
  "C) Armonia e continuità": "C) Harmony and continuity",
  "Quanti colori usa una triade?": "How many colors does a triad use?",
  "A) Due": "A) Two",
  "B) Tre": "B) Three",
  "C) Quattro": "C) Four",
  "Che forma disegnano i colori di una triade sulla ruota?": "What shape do the colors of a triad form on the wheel?",
  "A) Un triangolo": "A) A triangle",
  "B) Un quadrato": "B) A square",
  "C) Una linea": "C) A line",
  "Quale di queste è una triade?": "Which of these is a triad?",
  "A) Blu + Blu-verde + Verde": "A) Blue + Blue-green + Green",
  "B) Rosso + Verde": "B) Red + Green",
  "C) Rosso + Giallo + Blu": "C) Red + Yellow + Blue",
  "Da cosa parte uno schema split complementare?": "What is a split complementary scheme based on?",
  "A) Da un colore e dai due vicini al suo complementare": "A) A color and the two neighbors of its complement",
  "B) Da quattro colori equidistanti": "B) Four evenly spaced colors",
  "C) Da tre colori adiacenti": "C) Three adjacent colors",
  "Rispetto ai complementari diretti, il contrasto è…": "Compared with direct complementary colors, the contrast is…",
  "A) Nullo": "A) None",
  "B) Meno aggressivo": "B) Less aggressive",
  "C) Più aggressivo": "C) More aggressive",
  "Quale esempio è split complementare?": "Which example is split complementary?",
  "B) Blu + Azzurro": "B) Blue + Sky blue",
  "C) Blu con Giallo-Arancio e Rosso-Arancio": "C) Blue with Yellow-orange and Red-orange",
  "Come sono organizzati i quattro colori del rettangolo?": "How are the four colors of the rectangle organized?",
  "A) In due coppie complementari": "A) In two complementary pairs",
  "B) Tutti adiacenti": "B) All adjacent",
  "C) In un triangolo": "C) In a triangle",
  "Qual è un buon consiglio per usare questo schema?": "What is good advice for using this scheme?",
  "A) Usare tutti i colori in parti uguali": "A) Use all colors in equal amounts",
  "B) Scegliere un colore dominante": "B) Choose a dominant color",
  "C) Evitare i colori caldi": "C) Avoid warm colors",
  "Per quali progetti è adatto il rettangolo?": "Which projects is the rectangle suited to?",
  "A) Solo per il bianco e nero": "A) Only black and white ones",
  "B) Per palette monocromatiche": "B) Monochromatic palettes",
  "C) Per progetti complessi con molta varietà": "C) Complex projects with lots of variety",
  "Come sono disposti i colori del quadrato?": "How are the colors of the square arranged?",
  "A) Equidistanti tra loro": "A) Evenly spaced",
  "B) Tutti vicini": "B) All close together",
  "C) Solo due opposti": "C) Only two opposite",
  "Quanti colori usa lo schema quadrato?": "How many colors does the square scheme use?",
  "A) Tre": "A) Three",
  "B) Quattro": "B) Four",
  "C) Sei": "C) Six",
  "Che tipo di design produce?": "What kind of design does it produce?",
  "A) Spento e neutro": "A) Dull and neutral",
  "B) Monocromatico": "B) Monochromatic",
  "C) Energico e molto colorato": "C) Energetic and very colorful",
  "E se a leggerli fosse una macchina?": "What if a machine read them?",
  "Nell'installazione di CHROMA un'intelligenza artificiale attribuisce ai colori emozioni che non può conoscere. Confronta la tua lettura con la sua.": "In the CHROMA installation, an artificial intelligence attributes to colors emotions it cannot know. Compare your reading with its own.",
  "Prova la sovrainterpretazione cromatica ›": "Try chromatic overinterpretation ›"
};
