const UK = {
  "Benvenuto in": "Вітаємо в",
  "L’applicazione che ti insegna": "Застосунок, який навчає",
  "i significati dei colori": "значень кольорів",
  "Impara con Chroma": "Навчайся з Chroma",
  "Impara": "Навчайся",
  "Approfondisci la teoria": "Поглиблюй теорію",
  "e la psicologia dei colori": "та психологію кольорів",
  "con lezioni interattive.": "за допомогою інтерактивних уроків.",
  "Gioca e impara": "Грай і навчайся",
  "Completa quiz, missioni": "Проходь вікторини, місії",
  "e sfide per sbloccare": "та виклики, щоб відкрити",
  "nuovi colori e badge!": "нові кольори й значки!",
  "Inizia": "Почати",
  "📲 Installa CHROMA per usarla a schermo intero": "📲 Встанови CHROMA, щоб відкривати її на весь екран",
  "Installa": "Встановити",
  "Ciao,": "Привіт,",
  "Pronto a scoprire qualcosa di nuovo sui colori oggi?": "Готовий дізнатися сьогодні щось нове про кольори?",
  "Streak": "Серія",
  "Livello": "Рівень",
  "Sfida del giorno": "Виклик дня",
  "Missioni di oggi": "Сьогоднішні місії",
  "Vai alle missioni": "До місій",
  "Colore del giorno": "Колір дня",
  "Apri ›": "Відкрити ›",
  "Quest giornaliere": "Щоденні завдання",
  "Fammi vedere cosa hai imparato sui colori": "Покажи, що ти дізнався про кольори",
  "Verifica quello che hai imparato nelle ultime lezioni e scopri il tuo livello sulla psicologia dei colori": "Перевір, що ти вивчив на останніх уроках, і дізнайся свій рівень із психології кольору",
  "I tuoi colori sbloccati": "Твої відкриті кольори",
  "Aiutaci a insegnare qualcosa di nuovo a Chroma!": "Допоможи навчити Chroma чогось нового!",
  "Il nostro modello di AI per la critica del colore": "Наша модель ШІ для критики кольору",
  "entra sul nostro sito": "перейти на наш сайт",
  "Scopri": "Досліджуй",
  "Strumenti": "Інструменти",
  "Laboratorio": "Лабораторія",
  "Ruota dei colori, codici e armonie": "Колірне коло, коди та гармонії",
  "Colori da una foto": "Кольори з фото",
  "Estrai e interpreta una palette": "Витягни та інтерпретуй палітру",
  "Le mie palette": "Мої палітри",
  "Lezioni": "Уроки",
  "Quest": "Завдання",
  "Vediamo cosa hai imparato sui colori": "Подивімося, що ти дізнався про кольори",
  "Missioni attive": "Активні місії",
  "Tutte le missioni ›": "Усі місії ›",
  "Percorso guidato": "Навчальний маршрут",
  "Altre lezioni - Combinazioni di colori": "Інші уроки — поєднання кольорів",
  "Dettaglio lezione": "Урок",
  "Curiosità": "Цікавий факт",
  "Come funziona": "Як це працює",
  "Quando usarla": "Коли використовувати",
  "Consulta la teoria": "Переглянути теорію",
  "Profilo": "Профіль",
  "Completamento di CHROMA": "Проходження CHROMA",
  "Colori sbloccati": "Кольори",
  "Tempo totale": "Загальний час",
  "XP totali": "Усього XP",
  "Ultimi 7 giorni": "Останні 7 днів",
  "Minuti": "Хвилини",
  "I tuoi titoli": "Твої звання",
  "titoli sbloccati · storico dei livelli": "відкритих звань · історія рівнів",
  "Condividi il tuo profilo": "Поділитися профілем",
  "I tuoi progressi": "Твій прогрес",
  "Quest completate": "Виконані завдання",
  "Badges": "Значки",
  "Le tue statistiche": "Твоя статистика",
  "Lezioni completate": "Пройдені уроки",
  "Quiz completati": "Пройдені вікторини",
  "Missioni completate": "Виконані місії",
  "Giorni in streak": "Днів поспіль",
  "Badge": "Значки",
  "Tutti": "Усі",
  "Ottenuti": "Отримані",
  "Bloccati": "Заблоковані",
  "Esplora": "Огляд",
  "Palette personali": "Власні палітри",
  "＋ Crea una palette con i tuoi colori": "＋ Створи палітру зі своїх кольорів",
  "Condividi la palette": "Поділитися палітрою",
  "Missioni": "Місії",
  "Percorso": "Маршрут",
  "Oggi": "Сьогодні",
  "Speciali": "Особливі",
  "Completa lezioni e quiz per ottenere XP e sbloccare nuovi colori.": "Проходь уроки та вікторини, щоб отримувати XP і відкривати нові кольори.",
  "Si rinnovano ogni giorno e danno XP extra per salire di livello.": "Оновлюються щодня й дають додаткові XP для нового рівня.",
  "Torna ogni giorno: con la serie di giorni consecutivi sblocchi i colori speciali.": "Повертайся щодня: серія днів поспіль відкриває особливі кольори.",
  "Dettaglio missione": "Місія",
  "Progresso": "Прогрес",
  "Reward": "Нагорода",
  "Reward ottenuto": "Нагороду отримано",
  "Reward ottenuto!": "Нагороду отримано!",
  "Hai guadagnato:": "Ти отримав:",
  "Ottimo!": "Чудово!",
  "Lezione completata": "Урок пройдено",
  "Torna alle lezioni": "Повернутися до уроків",
  "Quiz completato!": "Вікторину пройдено!",
  "Risultato": "Результат",
  "Risposte corrette": "Правильні відповіді",
  "Accuratezza": "Точність",
  "Ricompense": "Нагороди",
  "Nuovo badge!": "Новий значок!",
  "Rispondi correttamente a tutte le domande per sbloccare il colore!": "Дай правильні відповіді на всі запитання, щоб відкрити колір!",
  "Torna ai quiz": "Повернутися до вікторин",
  "Quiz sui colori": "Вікторини про кольори",
  "8 colori, dal rosso al nero · 8 quiz": "8 кольорів, від червоного до чорного · 8 вікторин",
  "Quiz sulle combinazioni dei colori": "Вікторини про поєднання кольорів",
  "Combinazione dei colori": "Поєднання кольорів",
  "Le basi delle combinazioni · Armonie di colore · 6 quiz": "Основи поєднань · Колірні гармонії · 6 вікторин",
  "Quiz sul colore digitale": "Вікторини про цифровий колір",
  "RGB, HEX, HSL, CMYK e contrasto · 5 quiz": "RGB, HEX, HSL, CMYK і контраст · 5 вікторин",
  "Allenamento dell'occhio": "Тренування ока",
  "Dal codice HEX al colore": "Від коду HEX до кольору",
  "Ordina per luminosità": "Упорядкуй за яскравістю",
  "Il colore opposto sulla ruota": "Протилежний колір на колі",
  "Fai 3 su 3 in un quiz per sbloccare un nuovo colore e usarlo come tema dell'app.": "Набери 3 з 3 у вікторині, щоб відкрити новий колір і використати його як тему застосунку.",
  "Combinazione colori": "Поєднання кольорів",
  "Tocca un colore sbloccato per usarlo come tema di tutta l'app.": "Торкнися відкритого кольору, щоб зробити його темою всього застосунку.",
  "Tema attivo": "Активна тема",
  "Ripristina": "Скинути",
  "La tua tavolozza": "Твоя палітра кольорів",
  "Nome": "Назва",
  "Scegli fino a 6 colori": "Обери до 6 кольорів",
  "Puoi usare solo i colori che hai sbloccato. Completa quiz e missioni per averne altri!": "Можна використовувати лише відкриті кольори. Проходь вікторини й місії, щоб отримати більше!",
  "Salva palette": "Зберегти палітру",
  "Impostazioni": "Налаштування",
  "Il tuo nome": "Твоє ім'я",
  "Aspetto": "Вигляд",
  "Automatico": "Авто",
  "Chiaro": "Світлий",
  "Scuro": "Темний",
  "Colore del tema": "Колір теми",
  "Lingua": "Мова",
  "La lingua cambia da sola se scrivi il tuo nome con un altro alfabeto.": "Мова змінюється автоматично, якщо написати ім'я іншою абеткою.",
  "Installa l'app sul telefono": "Встановити застосунок на телефон",
  "Cerca aggiornamenti": "Перевірити оновлення",
  "Azzera tutti i progressi": "Скинути весь прогрес",
  "🧪 Modalità demo": "🧪 Демо-режим",
  "Simula i progressi per provare o presentare l'app.": "Імітуй прогрес, щоб випробувати чи презентувати застосунок.",
  "+1 livello": "+1 рівень",
  "+1 giorno di streak": "+1 день серії",
  "Completa le lezioni": "Пройти уроки",
  "+5 quiz fatti": "+5 вікторин",
  "Completa le missioni": "Виконати місії",
  "Sblocca tutti i badge": "Відкрити всі значки",
  "✨ Sblocca i colori segreti": "✨ Відкрити секретні кольори",
  "⭐ Simula utente esperto": "⭐ Досвідчений користувач",
  "↺ Nuovo utente (azzera tutto)": "↺ Новий користувач (скинути все)",
  "Chiudi": "Закрити",
  "Conferma": "Підтвердити",
  "Immagine profilo": "Фото профілю",
  "Carica una tua foto": "Завантажити своє фото",
  "Oppure scegli un avatar": "Або обери аватар",
  "Alcuni avatar si sbloccano salendo di livello.": "Деякі аватари відкриваються з новими рівнями.",
  "Ogni livello ti dà un nuovo soprannome. Tocca un titolo ottenuto per mostrarlo nel profilo.": "Кожен рівень дає нове звання. Торкнися отриманого звання, щоб показувати його в профілі.",
  "Hai completato CHROMA": "Ти пройшов CHROMA",
  "Colori segreti sbloccati!": "Секретні кольори відкрито!",
  "4 colorazioni animate, riservate a chi ha finito tutto il percorso.": "4 анімовані теми лише для тих, хто пройшов увесь маршрут.",
  "Scoprili": "Переглянути",
  "Più tardi": "Пізніше",
  "Salva": "Зберегти",
  "Nuovo titolo sbloccato": "Нове звання",
  "Fantastico!": "Чудово!",
  "Tocca o trascina sulla ruota: il giro sceglie la tinta, la distanza dal centro la saturazione. La luminosità si regola qui sotto.": "Торкнися або проведи по колу: положення на колі задає відтінок, відстань від центру — насиченість. Яскравість регулюється нижче.",
  "Copia": "Копіювати",
  "Somiglia a": "Схожий на",
  "Emozioni": "Емоції",
  "Armonie": "Гармонії",
  "Nessuna": "Немає",
  "Split": "Спліт",
  "Come lo vede chi è daltonico": "Як його бачать люди з дальтонізмом",
  "Vista normale": "Звичайний зір",
  "Protanopia": "Протанопія",
  "Deuteranopia": "Дейтеранопія",
  "Tritanopia": "Тританопія",
  "Salva come palette": "Зберегти як палітру",
  "Scatta o scegli una foto: CHROMA ne estrae i colori principali, li misura e prova a interpretarli. La foto resta sul tuo dispositivo.": "Зроби або обери фото: CHROMA виділить основні кольори, виміряє їх і спробує інтерпретувати. Фото залишається на твоєму пристрої.",
  "Scatta una foto": "Зробити фото",
  "Dalla galleria": "З галереї",
  "Prova con un esempio": "Спробуй на прикладі",
  "Riduce la foto": "Зменшує фото",
  "L'immagine viene ridotta a pochi pixel per lavorare velocemente.": "Зображення зменшується до невеликої кількості пікселів, щоб працювати швидко.",
  "Raggruppa i colori": "Групує кольори",
  "Un algoritmo (k-means) unisce i pixel simili in 5 colori principali.": "Алгоритм (k-means) об'єднує схожі пікселі в 5 основних кольорів.",
  "Li interpreta": "Інтерпретує їх",
  "Misura temperatura, saturazione e luce e li collega ai significati delle lezioni.": "Вимірює температуру, насиченість і світло та пов'язує їх зі значеннями з уроків.",
  "La palette": "Палітра",
  "Le misure": "Вимірювання",
  "Interpretazione": "Інтерпретація",
  "È un'interpretazione algoritmica: collega i colori ai significati studiati nelle lezioni, ma il senso di un'immagine dipende sempre dal contesto.": "Це алгоритмічна інтерпретація: вона пов'язує кольори зі значеннями з уроків, але сенс зображення завжди залежить від контексту.",
  "Analizza un'altra foto": "Проаналізувати інше фото",
  "Come ti chiami?": "Як тебе звати?",
  "Vedi tutti": "Переглянути всі",
  "Indietro": "Назад",
  "Cambia immagine del profilo": "Змінити фото профілю",
  "Es. La mia estate": "Напр. Моє літо",
  "Anteprima della card": "Попередній перегляд картки",
  "Arance": "Апельсини",
  "Esempio blu": "Синій приклад",
  "Esempio viola": "Фіолетовий приклад",
  "Home": "Головна",
  "Serie: {m}": "Серія: {m}",
  "Missione: {m}": "Місія: {m}",
  "Completa tutte le lezioni, i quiz e le missioni": "Пройди всі уроки, вікторини та місії",
  "Benvenuto": "друже",
  "Ospite": "Гість",
  "h": "год",
  "min": "хв",
  "🏆 Livello massimo raggiunto: hai completato tutto CHROMA!": "🏆 Максимальний рівень: ти пройшов увесь CHROMA!",
  "Completa tutto il percorso per diventare <b>{t}</b> ({c})": "Пройди весь маршрут, щоб стати <b>{t}</b> ({c})",
  "Ancora <b>{xp}</b> XP per diventare <b>{t}</b>": "Ще <b>{xp}</b> XP до звання <b>{t}</b>",
  "✓ Completata": "✓ Пройдено",
  "Prima la teoria": "Спершу теорія",
  "✓ Completato": "✓ Пройдено",
  "Colore da riscattare": "Колір чекає",
  "Record {n}/3": "Рекорд {n}/3",
  "{a} / {b} lette": "{a} / {b} прочитано",
  "{a} / {b} completate": "{a} / {b} пройдено",
  "{a} / {b} completati": "{a} / {b} пройдено",
  "5 min · livello base": "5 хв · базовий рівень",
  "Lezione completata!": "Урок пройдено!",
  "Lezione ripassata!": "Урок повторено!",
  "Hai guadagnato": "Ти отримав",
  "Gli XP di questa lezione li hai già ottenuti": "XP за цей урок ти вже отримав",
  "Rifai il quiz": "Пройти вікторину знову",
  "Fai il quiz": "Пройти вікторину",
  "avanti": "далі",
  "Quiz": "Вікторина",
  "Quiz (elenco)": "Вікторини",
  "✓ Letta": "✓ Прочитано",
  "Arriva in fondo alla lezione per sbloccare il quiz": "Дочитай урок до кінця, щоб відкрити вікторину",
  "Prima studia la teoria: poi il quiz si sblocca": "Спершу вивчи теорію — тоді вікторина відкриється",
  "Esatto!": "Правильно!",
  "Non proprio… la risposta giusta è evidenziata.": "Не зовсім… правильну відповідь виділено.",
  "XP già ottenuti": "XP уже отримано",
  "Già riscattato": "Уже отримано",
  "Riscatta": "Отримати",
  "Tema attivo ✓": "Тема активна ✓",
  "Usa come tema": "Зробити темою",
  "Tema “{n}” applicato": "Тему «{n}» застосовано",
  "Riscattato ✓": "Отримано ✓",
  "Nuovo colore sbloccato: {n}": "Новий колір відкрито: {n}",
  "Tema segreto “{n}” attivato": "Секретну тему «{n}» увімкнено",
  "Tema originale": "Початкова тема",
  "Tema {n}": "Тема {n}",
  "Come si sblocca: {h}": "Як відкрити: {h}",
  "Tema originale ripristinato": "Початкову тему відновлено",
  "Studia “{n}” e fai 3 su 3 nel quiz": "Вивчи «{n}» і набери 3 з 3 у вікторині",
  "Fai 3 su 3 in questo quiz per sbloccarlo": "Набери 3 з 3 у цій вікторині, щоб відкрити його",
  "Continua a giocare per sbloccarlo": "Грай далі, щоб відкрити його",
  "Colori segreti": "Секретні кольори",
  "Raggiungi il livello {l} completando tutto CHROMA per sbloccare 4 colorazioni animate. Completamento: {p}%": "Досягни рівня {l}, пройшовши весь CHROMA, щоб відкрити 4 анімовані теми. Проходження: {p}%",
  "Attivo": "Активна",
  "Solo XP": "Лише XP",
  "Completata! Tocca per riscattare": "Виконано! Торкнися, щоб отримати",
  "Riscattata ✓": "Отримано ✓",
  "Hai completato le missioni di oggi!": "Ти виконав сьогоднішні місії!",
  "Missioni di oggi: {a} / {b} completate": "Сьогоднішні місії: {a} / {b} виконано",
  "Missione del percorso": "Місія маршруту",
  "Missione giornaliera": "Щоденна місія",
  "Missione speciale": "Особлива місія",
  "Già riscattata": "Уже отримано",
  "Riscatta reward": "Отримати нагороду",
  "personale": "власна",
  "Opzioni": "Параметри",
  "Apri": "Відкрити",
  "Crea una palette simile": "Створити схожу палітру",
  "{n} (mia)": "{n} (моя)",
  "Condividi": "Поділитися",
  "Modifica": "Редагувати",
  "Usa il primo colore come tema": "Зробити перший колір темою",
  "Apri nel Laboratorio": "Відкрити в Лабораторії",
  "Elimina": "Видалити",
  "Eliminare la palette?": "Видалити палітру?",
  "“{n}” verrà cancellata.": "«{n}» буде видалено.",
  "Palette eliminata": "Палітру видалено",
  "Usa {n} come tema": "Зробити {n} темою",
  "Apri {n} nel Laboratorio": "Відкрити {n} в Лабораторії",
  "Creata da te con {n} colori. Tocca un colore sbloccato qui sopra per usarlo come tema dell'app, o un codice per aprirlo nel Laboratorio.": "Твоя палітра з {n} кольорів. Торкнися відкритого кольору вгорі, щоб зробити його темою, або коду, щоб відкрити його в Лабораторії.",
  "Creata da te con {n} colori. Tocca un colore qui sopra per aprirlo nel Laboratorio e scoprirne i codici.": "Твоя палітра з {n} кольорів. Торкнися кольору вгорі, щоб відкрити його в Лабораторії й побачити коди.",
  "Modifica palette": "Редагувати палітру",
  "Nuova palette": "Нова палітра",
  "Massimo 6 colori per palette": "Не більше 6 кольорів у палітрі",
  "Dai un nome alla palette": "Дай палітрі назву",
  "Scegli almeno 2 colori": "Обери щонайменше 2 кольори",
  "Palette aggiornata": "Палітру оновлено",
  "Palette creata!": "Палітру створено!",
  "Annulla": "Скасувати",
  "Nome salvato": "Ім'я збережено",
  "Azzerare tutto?": "Скинути все?",
  "XP, livelli, lezioni, colori, badge e palette torneranno a zero e ripartirà l'onboarding.": "XP, рівні, уроки, кольори, значки й палітри буде скинуто, а вступ почнеться спочатку.",
  "Titolo aggiornato": "Звання оновлено",
  "Scegli il titolo da mostrare": "Обери звання для профілю",
  "Vedi tutti i titoli…": "Усі звання…",
  "prima del registro": "до початку історії",
  "Livello {l}": "Рівень {l}",
  "Prossimo · mancano {xp} XP": "Наступне · ще {xp} XP",
  "In mostra": "У профілі",
  "Ora mostri: {n}": "Тепер у профілі: {n}",
  "La tua foto": "Твоє фото",
  "Si sblocca al livello {l}": "Відкривається на рівні {l}",
  "Avatar aggiornato": "Аватар оновлено",
  "Foto del profilo aggiornata": "Фото профілю оновлено",
  "Immagine non valida": "Некоректне зображення",
  "quiz": "вікторин",
  "lezioni": "уроків",
  "{u} in 7 giorni": "{u} за 7 днів",
  "media al giorno": "в середньому за день",
  "giorni attivi": "активних днів",
  "Il tuo giorno migliore: <b>{d}</b> ({v} {u})": "Твій найкращий день: <b>{d}</b> ({v} {u})",
  "Il livello {l} si sblocca solo completando tutto": "Рівень {l} відкривається лише після проходження всього",
  "+1 ora di studio": "+1 година навчання",
  "Streak: {n} giorni": "Серія: {n} дн.",
  "{n} lezioni completate (+{xp} XP)": "Пройдено уроків: {n} (+{xp} XP)",
  "Lezioni già tutte completate": "Усі уроки вже пройдено",
  "+5 quiz completati": "+5 пройдених вікторин",
  "Tutte le missioni sono pronte da riscattare!": "Усі місії готові — можна отримати нагороди!",
  "Tutti i {n} colori sbloccati": "Усі {n} кольорів відкрито",
  "Tutti i badge sbloccati": "Усі значки відкрито",
  "Profilo da utente esperto caricato": "Завантажено профіль досвідченого користувача",
  "Nuovo utente?": "Новий користувач?",
  "Tutti i progressi verranno azzerati e ripartirà l'onboarding.": "Увесь прогрес буде скинуто, а вступ почнеться спочатку.",
  "Ancora {n}…": "Ще {n}…",
  "CHROMA è già installata": "CHROMA вже встановлено",
  "Installa CHROMA su iPhone": "Встановити CHROMA на iPhone",
  "Installa CHROMA": "Встановити CHROMA",
  "Apri questa pagina con <b>Safari</b>": "Відкрий цю сторінку в <b>Safari</b>",
  "Tocca il tasto <b>Condividi</b> (il quadrato con la freccia ↑)": "Торкнися кнопки <b>Поділитися</b> (квадрат зі стрілкою ↑)",
  "Scegli <b>Aggiungi a Home</b> e poi <b>Aggiungi</b>": "Обери <b>На початковий екран</b>, а потім <b>Додати</b>",
  "Apri CHROMA dall'icona: sarà a schermo intero": "Відкривай CHROMA з іконки — вона буде на весь екран",
  "Apri il menu del browser <b>⋮</b>": "Відкрий меню браузера <b>⋮</b>",
  "Scegli <b>Installa app</b> o <b>Aggiungi a schermata Home</b>": "Обери <b>Встановити застосунок</b> або <b>Додати на головний екран</b>",
  "Ho capito": "Зрозуміло",
  "È disponibile una nuova versione di CHROMA": "Доступна нова версія CHROMA",
  "Aggiorna ora": "Оновити зараз",
  "Aggiornamento in corso…": "Оновлення…",
  "Aggiornare l'app?": "Оновити застосунок?",
  "Scarico l'ultima versione di CHROMA. I tuoi progressi restano salvati.": "Буде завантажено останню версію CHROMA. Твій прогрес збережеться.",
  "Tesi magistrale": "Магістерська робота",
  "CHROMA aggiornata all'ultima versione ✨": "CHROMA оновлено до останньої версії ✨",
  "Copiato: {v}": "Скопійовано: {v}",
  "Solo testi grandi": "Лише великий текст",
  "Poco leggibile ✗": "Погано читається ✗",
  "Palette di sfumature salvata": "Палітру відтінків збережено",
  "Armonia salvata in Le mie palette": "Гармонію збережено в «Мої палітри»",
  "Prevalgono i colori caldi ({p}), che di solito vengono associati a energia, calore e vicinanza.": "Переважають теплі кольори ({p}), які зазвичай асоціюють з енергією, теплом і близькістю.",
  "Prevalgono i colori freddi ({p}), che di solito vengono associati a calma, distanza e riflessione.": "Переважають холодні кольори ({p}), які зазвичай асоціюють зі спокоєм, дистанцією та роздумами.",
  "Prevalgono i toni neutri ({p}): l'immagine risulta sobria e i pochi colori accesi risaltano di più.": "Переважають нейтральні тони ({p}): зображення стримане, а нечисленні яскраві кольори виділяються сильніше.",
  "I colori sono molto saturi: l'effetto è vivace.": "Кольори дуже насичені: ефект яскравий.",
  "La saturazione è media: i colori non sono né spenti né accesi.": "Насиченість середня: кольори ні бляклі, ні яскраві.",
  "I colori sono tenui e poco saturi.": "Кольори м'які та малонасичені.",
  "L'immagine è luminosa.": "Зображення світле.",
  "La luminosità è media.": "Яскравість середня.",
  "L'immagine è scura.": "Зображення темне.",
  "Il colore principale è vicino al tono “{n}”, che nelle lezioni viene associato a {e}.": "Основний колір близький до відтінку «{n}», який в уроках асоціюють з такими поняттями: {e}.",
  "principale": "основний",
  "Temperatura": "Температура",
  "Calda": "Тепла",
  "Fredda": "Холодна",
  "Equilibrata": "Урівноважена",
  "Saturazione": "Насиченість",
  "Luminosità": "Яскравість",
  "Contrasto interno": "Внутрішній контраст",
  "Molto forte: luci e ombre ben separate.": "Дуже сильний: світло й тіні чітко розділені.",
  "Buono: luci e ombre sono ben distinte.": "Добрий: світло й тіні добре розрізняються.",
  "Medio: toni abbastanza ravvicinati.": "Середній: тони досить близькі.",
  "Basso: toni molto simili tra loro.": "Низький: тони дуже схожі між собою.",
  "Neutra": "Нейтральна",
  "Pochi colori saturi: domina la luce più della tinta.": "Мало насичених кольорів: світло важить більше за відтінок.",
  "Monocromatica / analoga": "Монохромна / аналогова",
  "Le tinte sono vicine sulla ruota: l'insieme risulta coerente.": "Відтінки розташовані поруч на колі: ціле виглядає узгоджено.",
  "Con contrasto complementare": "З додатковим контрастом",
  "Ci sono tinte quasi opposte sulla ruota: l'immagine ha un forte contrasto di colore.": "Є майже протилежні відтінки на колі: зображення має сильний колірний контраст.",
  "Varia": "Різноманітна",
  "Le tinte sono distribuite sulla ruota senza uno schema preciso.": "Відтінки розподілені по колу без чіткої схеми.",
  "Non riesco a leggere questa immagine": "Не вдається прочитати це зображення",
  "Dalla foto": "З фото",
  "Palette della foto salvata": "Палітру з фото збережено",
  "Punti {n}": "Бали: {n}",
  "Non proprio: quello giusto è evidenziato.": "Не зовсім: правильний варіант виділено.",
  "Ordine perfetto!": "Ідеальний порядок!",
  "Quasi: l'ordine giusto è {o} (posizioni da sinistra).": "Майже: правильний порядок — {o} (позиції зліва).",
  "Round {n} / 5": "Раунд {n} / 5",
  "Fine!": "Кінець!",
  "Hai fatto {n} su 5.": "Твій результат: {n} з 5.",
  "Ottimo occhio!": "Чудове око!",
  "Riprova per allenarti ancora.": "Спробуй ще раз, щоб потренуватися.",
  "Record: {n} / 5": "Рекорд: {n} / 5",
  "Rigioca": "Грати знову",
  "Record {n}/5": "Рекорд {n}/5",
  "Da provare": "Ще не пробував",
  "Preparo la tua card…": "Готую твою картку…",
  "{p}% di CHROMA completato": "CHROMA пройдено на {p}%",
  "giorni di fila": "днів поспіль",
  "di studio": "навчання",
  "I miei colori · {a}/{b}": "Мої кольори · {a}/{b}",
  "Il mio profilo CHROMA": "Мій профіль CHROMA",
  "Palette creata con CHROMA": "Палітру створено в CHROMA",
  "Combinazioni di colori": "Поєднання кольорів",
  "Il colore nel digitale": "Колір у цифровому світі",
  "Psicologia del colore": "Психологія кольору",
  "Significato": "Значення",
  "La tua palette": "Твоя палітра",
  "Emozioni associate": "Пов'язані емоції",
  "Colori": "Кольори",
  "Indovina il colore": "Вгадай колір",
  "Quale colore corrisponde a questo codice HEX?": "Який колір відповідає цьому коду HEX?",
  "Trova il complementare": "Знайди додатковий колір",
  "Quale colore sta dalla parte opposta della ruota?": "Який колір розташований з протилежного боку кола?",
  "Dal chiaro allo scuro": "Від світлого до темного",
  "Tocca i colori dal più chiaro al più scuro.": "Торкайся кольорів від найсвітлішого до найтемнішого.",
  "Grigio perla": "Перлинно-сірий",
  "Grigio ardesia": "Сланцево-сірий",
  "Rosso": "Червоний",
  "Quiz sul rosso": "Вікторина про червоний",
  "Arancione": "Помаранчевий",
  "Quiz sull'arancione": "Вікторина про помаранчевий",
  "Giallo": "Жовтий",
  "Quiz sul giallo": "Вікторина про жовтий",
  "Verde": "Зелений",
  "Quiz sul verde": "Вікторина про зелений",
  "Blu": "Синій",
  "Quiz sul blu": "Вікторина про синій",
  "Viola": "Фіолетовий",
  "Quiz sul viola": "Вікторина про фіолетовий",
  "Bianco": "Білий",
  "Quiz sul bianco": "Вікторина про білий",
  "Nero": "Чорний",
  "Quiz sul nero": "Вікторина про чорний",
  "Turchese": "Бірюзовий",
  "Quiz Complementari": "Вікторина «Додаткові»",
  "Lime": "Лаймовий",
  "Quiz Analoghi": "Вікторина «Аналогові»",
  "Magenta": "Маджента",
  "Quiz Triade": "Вікторина «Тріада»",
  "Corallo": "Кораловий",
  "Quiz Split compl.": "Вікторина «Розщеплені дод.»",
  "Oliva": "Оливковий",
  "Quiz Rettangolo": "Вікторина «Прямокутник»",
  "Petrolio": "Петролевий",
  "Quiz Quadrato": "Вікторина «Квадрат»",
  "Carminio": "Карміновий",
  "Rosa": "Рожевий",
  "Terracotta": "Теракотовий",
  "Oro": "Золотий",
  "Verde bosco": "Лісовий зелений",
  "Salvia": "Шавлієвий",
  "Menta": "М'ятний",
  "Azzurro": "Блакитний",
  "Blu notte": "Нічний синій",
  "Lavanda": "Лавандовий",
  "Prugna": "Сливовий",
  "Marrone": "Коричневий",
  "Verde neon": "Неоново-зелений",
  "Quiz RGB": "Вікторина RGB",
  "Fucsia": "Фуксія",
  "Quiz HEX": "Вікторина HEX",
  "Oltremare": "Ультрамарин",
  "Quiz HSL": "Вікторина HSL",
  "Ghiaccio": "Крижаний",
  "Quiz CMYK": "Вікторина CMYK",
  "Pesca": "Персиковий",
  "Quiz Contrasto": "Вікторина «Контраст»",
  "Crema": "Кремовий",
  "Lampone": "Малиновий",
  "Rossi": "Червоні",
  "Arancioni e terre": "Помаранчеві та земляні",
  "Gialli": "Жовті",
  "Verdi-gialli": "Жовто-зелені",
  "Verdi": "Зелені",
  "Ciano": "Ціан",
  "Rosa e magenta": "Рожеві та маджента",
  "Neutri": "Нейтральні",
  "passione": "пристрасть",
  "energia": "енергія",
  "urgenza": "терміновість",
  "entusiasmo": "ентузіазм",
  "calore": "тепло",
  "creatività": "креативність",
  "ottimismo": "оптимізм",
  "luce": "світло",
  "curiosità": "допитливість",
  "freschezza": "свіжість",
  "vitalità": "життєва сила",
  "crescita": "зростання",
  "natura": "природа",
  "equilibrio": "рівновага",
  "calma": "спокій",
  "chiarezza": "ясність",
  "tecnologia": "технології",
  "fiducia": "довіра",
  "stabilità": "стабільність",
  "mistero": "таємничість",
  "lusso": "розкіш",
  "gioia": "радість",
  "romanticismo": "романтика",
  "originalità": "оригінальність",
  "eleganza": "елегантність",
  "semplicità": "простота",
  "Apprendista": "Учень",
  "Curioso del colore": "Допитливий до кольору",
  "Esploratore del colore": "Дослідник кольору",
  "Osservatore di sfumature": "Спостерігач відтінків",
  "Pittore alle prime armi": "Художник-початківець",
  "Mescolatore di tinte": "Змішувач барв",
  "Cacciatore di contrasti": "Мисливець за контрастами",
  "Pittore sfumato": "Художник сфумато",
  "Alchimista dei pigmenti": "Алхімік пігментів",
  "Maestro del colore": "Майстер кольору",
  "Custode della ruota cromatica": "Хранитель колірного кола",
  "Architetto delle armonie": "Архітектор гармоній",
  "Poeta della luce": "Поет світла",
  "Virtuoso della palette": "Віртуоз палітри",
  "Visionario cromatico": "Колірний візіонер",
  "Signore delle tonalità": "Володар тонів",
  "Guru del colore": "Гуру кольору",
  "Mago dello spettro": "Чарівник спектра",
  "Oracolo dei colori": "Оракул кольорів",
  "Leggenda cromatica": "Колірна легенда",
  "Primi passi": "Перші кроки",
  "Completa la tua prima lezione.": "Пройди свій перший урок.",
  "Vai alle lezioni": "До уроків",
  "A metà strada": "На півдорозі",
  "Completa 4 lezioni.": "Пройди 4 уроки.",
  "Studente dei colori": "Студент кольорів",
  "Completa tutte le 8 lezioni di psicologia del colore.": "Пройди всі 8 уроків із психології кольору.",
  "Primo 3 su 3": "Перші 3 з 3",
  "Rispondi correttamente a tutte le domande di un quiz.": "Дай правильні відповіді на всі запитання однієї вікторини.",
  "Vai ai quiz": "До вікторин",
  "Esperto di psicologia": "Знавець психології",
  "Fai 3 su 3 in tutti gli 8 quiz sui colori.": "Набери 3 з 3 в усіх 8 вікторинах про кольори.",
  "Teorico delle armonie": "Теоретик гармоній",
  "Leggi la teoria di tutte le 6 combinazioni di colori, fino alla seconda pagina.": "Прочитай теорію всіх 6 поєднань кольорів до другої сторінки.",
  "Vai alle combinazioni": "До поєднань",
  "Armonia perfetta": "Ідеальна гармонія",
  "Fai 3 su 3 in tutti i 6 quiz sulle combinazioni.": "Набери 3 з 3 в усіх 6 вікторинах про поєднання.",
  "Creativo": "Творчий",
  "Crea la tua prima palette personale con i colori sbloccati.": "Створи свою першу палітру з відкритих кольорів.",
  "Vai alle palette": "До палітр",
  "Grande collezione": "Велика колекція",
  "Sblocca 15 colori tra quiz e missioni.": "Відкрий 15 кольорів у вікторинах і місіях.",
  "I tuoi colori": "Твої кольори",
  "Nativo digitale": "Цифровий абориген",
  "Completa le 5 lezioni del percorso “Il colore nel digitale”.": "Пройди 5 уроків розділу «Колір у цифровому світі».",
  "Occhio digitale": "Цифрове око",
  "Fai 3 su 3 in tutti i 5 quiz sul colore digitale.": "Набери 3 з 3 в усіх 5 вікторинах про цифровий колір.",
  "Sperimentatore": "Експериментатор",
  "Crea un'armonia nel Laboratorio e salvala come palette.": "Створи гармонію в Лабораторії та збережи її як палітру.",
  "Apri il Laboratorio": "Відкрити Лабораторію",
  "Detective del colore": "Детектив кольору",
  "Analizza i colori di una tua foto con “Colori da una foto”.": "Проаналізуй кольори свого фото в розділі «Кольори з фото».",
  "Analizza una foto": "Проаналізувати фото",
  "Occhio allenato": "Натреноване око",
  "Fai almeno 4 su 5 in tutti e 3 i giochi dell'allenamento.": "Набери щонайменше 4 з 5 в усіх 3 тренувальних іграх.",
  "Vai ai giochi": "До ігор",
  "2 giorni di fila": "2 дні поспіль",
  "Apri CHROMA per 2 giorni consecutivi. Colore speciale!": "Відкривай CHROMA 2 дні поспіль. Особливий колір!",
  "Torna domani": "Повертайся завтра",
  "3 giorni di fila": "3 дні поспіль",
  "Apri CHROMA per 3 giorni consecutivi. Colore speciale!": "Відкривай CHROMA 3 дні поспіль. Особливий колір!",
  "4 giorni di fila": "4 дні поспіль",
  "Apri CHROMA per 4 giorni consecutivi. Colore speciale!": "Відкривай CHROMA 4 дні поспіль. Особливий колір!",
  "Completa o ripassa 1 lezione": "Пройди або повтори 1 урок",
  "Oggi completa una lezione nuova o ripassane una già fatta.": "Сьогодні пройди новий урок або повтори вже пройдений.",
  "Rispondi a 2 quiz": "Пройди 2 вікторини",
  "Oggi completa due quiz qualsiasi, anche già fatti.": "Сьогодні пройди дві будь-які вікторини, навіть уже пройдені.",
  "Fai un quiz perfetto": "Пройди вікторину без помилок",
  "Oggi rispondi correttamente a tutte le domande di un quiz.": "Сьогодні дай правильні відповіді на всі запитання однієї вікторини.",
  "Studia 5 minuti": "Навчайся 5 хвилин",
  "Resta nell'app a studiare almeno 5 minuti oggi.": "Сьогодні проведи в застосунку щонайменше 5 хвилин за навчанням.",
  "Studia ora": "Навчатися зараз",
  "Badge dello studente": "Значок студента",
  "Badge dello studioso": "Значок науковця",
  "Badge digitale": "Цифровий значок",
  "Badge sociale": "Соціальний значок",
  "Color Explorer": "Дослідник кольорів",
  "Raccogli 10 colori": "Збери 10 кольорів",
  "Completa le 8 lezioni di psicologia del colore": "Пройди 8 уроків із психології кольору",
  "3/3 in tutti gli 8 quiz di psicologia del colore": "3/3 в усіх 8 вікторинах із психології кольору",
  "3 giorni di fila": "3 дні поспіль",
  "Raggiungi il livello 10": "Досягни 10 рівня",
  "Completa le lezioni sul digitale": "Пройди уроки про цифровий колір",
  "4/5 in tutti i giochi": "4/5 в усіх іграх",
  "Collezionista": "Колекціонер",
  "Sblocca tutti i colori": "Відкрий усі кольори",
  "Classico": "Класичний",
  "Chroma": "Chroma",
  "Tavolozza": "Палітра",
  "Pennello": "Пензель",
  "Goccia": "Крапля",
  "Prisma": "Призма",
  "Sole": "Сонце",
  "Luna": "Місяць",
  "Foglia": "Листок",
  "Occhio": "Око",
  "Corona": "Корона",
  "Arcobaleno": "Веселка",
  "Colori caldi": "Теплі кольори",
  "I colori caldi comprendono principalmente le tonalità di rosso, arancione e giallo. Richiamano il sole e il fuoco e vengono associati a vitalità, entusiasmo e dinamismo.": "До теплих кольорів належать насамперед відтінки червоного, помаранчевого та жовтого. Вони нагадують про сонце й вогонь і асоціюються з життєвою силою, ентузіазмом і динамікою.",
  "Passione": "Пристрасть",
  "Energia": "Енергія",
  "Calore": "Тепло",
  "Entusiasmo": "Ентузіазм",
  "Urgenza": "Терміновість",
  "Colori freddi": "Холодні кольори",
  "I colori freddi comprendono principalmente le tonalità di blu, verde e viola. Richiamano l'acqua, il cielo e la vegetazione e vengono associati a calma, equilibrio e serenità.": "До холодних кольорів належать насамперед відтінки синього, зеленого та фіолетового. Вони нагадують про воду, небо й рослинність і асоціюються зі спокоєм, рівновагою та безтурботністю.",
  "Calma": "Спокій",
  "Stabilità": "Стабільність",
  "Fiducia": "Довіра",
  "Serenità": "Безтурботність",
  "Relax": "Розслаблення",
  "Mezzitoni": "Приглушені тони",
  "Qui con “mezzitoni” intendiamo colori smorzati: tinte a cui è stato aggiunto del grigio, meno sature e più morbide dei colori puri. Accostati tra loro creano un effetto armonioso ed equilibrato.": "Тут під «приглушеними тонами» ми маємо на увазі кольори з домішкою сірого: вони менш насичені й м'якші за чисті кольори. Поєднані разом, вони створюють гармонійне й урівноважене враження.",
  "Equilibrio": "Рівновага",
  "Armonia": "Гармонія",
  "Nel film “Grand Budapest Hotel” (2014) di Wes Anderson ogni epoca ha la sua palette: rosa e pastelli per gli anni Trenta, toni più spenti e freddi per gli anni Sessanta.": "У фільмі Веса Андерсона «Готель „Ґранд Будапешт“» (2014) кожна епоха має власну палітру: рожевий і пастельні тони для 1930-х, приглушеніші й холодніші — для 1960-х.",
  "Tutto lo spettro in movimento": "Увесь спектр у русі",
  "Aurora boreale": "Північне сяйво",
  "Verdi e viola che danzano": "Танець зеленого й фіолетового",
  "Tramonto": "Захід сонця",
  "Dall'arancio al magenta": "Від помаранчевого до мадженти",
  "Olografico": "Голографічний",
  "Riflessi iridescenti": "Райдужні переливи",
  "Protanopia: i rossi appaiono più scuri e si confondono con i verdi. Riguarda circa 1 uomo su 100. La simulazione è un'approssimazione.": "Протанопія: червоні відтінки здаються темнішими й плутаються із зеленими. Трапляється приблизно в 1 чоловіка зі 100. Симуляція є наближеною.",
  "Deuteranopia: verdi e rossi si confondono. Le difficoltà rosso-verde sono la forma più comune: contando le forme lievi riguardano circa 6 uomini su 100. La simulazione è un'approssimazione.": "Дейтеранопія: зелені й червоні відтінки плутаються. Порушення червоно-зеленого сприйняття — найпоширеніша форма: разом із легкими формами вони трапляються приблизно в 6 чоловіків зі 100. Симуляція є наближеною.",
  "Tritanopia: blu e gialli si confondono. È molto rara e riguarda allo stesso modo uomini e donne. La simulazione è un'approssimazione.": "Тританопія: сині й жовті відтінки плутаються. Вона дуже рідкісна й однаково трапляється в чоловіків і жінок. Симуляція є наближеною.",
  "Colore": "Колір",
  "Il significato del blu": "Значення синього",
  "Il blu è uno dei colori più apprezzati: in molti sondaggi internazionali risulta il preferito. È associato al cielo e all'acqua e, nella cultura occidentale, viene collegato a calma, fiducia e stabilità.": "Синій — один із найулюбленіших кольорів: у багатьох міжнародних опитуваннях він посідає перше місце. Він асоціюється з небом і водою, а в західній культурі — зі спокоєм, довірою та стабільністю.",
  "Per questo è molto usato da banche, aziende tecnologiche e istituzioni, che vogliono comunicare professionalità e affidabilità.": "Тому його часто використовують банки, технологічні компанії та установи, які хочуть передати професійність і надійність.",
  "Le tonalità più chiare tendono a evocare tranquillità e serenità, mentre quelle più scure vengono associate ad autorevolezza ed eleganza.": "Світліші відтінки зазвичай викликають відчуття спокою та безтурботності, а темніші асоціюються з авторитетом і елегантністю.",
  "Molti social network e aziende tecnologiche hanno un logo blu: è un colore che il pubblico associa facilmente a fiducia e sicurezza.": "Багато соціальних мереж і технологічних компаній мають синій логотип: цей колір люди легко пов'язують із довірою та безпекою.",
  "Il significato dell’arancione": "Значення помаранчевого",
  "L'arancione si ottiene mescolando rosso e giallo e sulla ruota cromatica si trova tra questi due colori. È un colore caldo e molto luminoso.": "Помаранчевий отримують, змішуючи червоний і жовтий, і на колірному колі він розташований між ними. Це теплий і дуже яскравий колір.",
  "Nella psicologia del colore viene associato all'entusiasmo, alla creatività e all'ottimismo: richiama l'attenzione in modo meno aggressivo del rosso.": "У психології кольору його пов'язують з ентузіазмом, креативністю та оптимізмом: він привертає увагу м'якше, ніж червоний.",
  "Nel design viene usato spesso per pulsanti e inviti all'azione, perché cattura lo sguardo e comunica un tono amichevole e informale.": "У дизайні його часто використовують для кнопок і закликів до дії, бо він притягує погляд і створює дружній, невимушений настрій.",
  "Il nome del colore viene da quello del frutto. In inglese antico, prima che l'arancia fosse conosciuta, questa tinta si chiamava geoluhread, cioè “giallo-rosso”.": "Назва кольору походить від назви фрукта. У давньоанглійській мові, коли апельсинів ще не знали, цей відтінок називали geoluhread, тобто «жовто-червоний».",
  "Il significato del viola": "Значення фіолетового",
  "Il viola si ottiene mescolando rosso e blu. Nell'antichità le tinture viola erano rarissime e costose, e per questo è stato a lungo considerato un colore prezioso.": "Фіолетовий отримують, змішуючи червоний і синій. У давнину фіолетові барвники були рідкісними й дорогими, тому цей колір довго вважали цінним.",
  "Nella cultura occidentale viene associato alla creatività, alla spiritualità e al mistero, ma anche al lusso e alla regalità.": "У західній культурі його асоціюють із креативністю, духовністю й таємничістю, а також із розкішшю та царственістю.",
  "Le tonalità chiare come il lilla vengono percepite come delicate e romantiche, mentre quelle profonde richiamano ricchezza e ambizione.": "Світлі відтінки, як-от бузковий, сприймаються як ніжні й романтичні, а глибокі нагадують про багатство та амбіції.",
  "Nell'antica Roma la porpora di Tiro si ricavava da migliaia di molluschi ed era costosissima: la toga interamente purpurea era riservata ai generali durante il trionfo e, più tardi, agli imperatori.": "У Стародавньому Римі тірський пурпур добували з тисяч молюсків, і він коштував надзвичайно дорого: повністю пурпурову тогу носили полководці під час тріумфу, а згодом — імператори.",
  "Il significato del rosso": "Значення червоного",
  "Il rosso è il colore visibile con la lunghezza d'onda più lunga ed è tra quelli che attirano più rapidamente lo sguardo. È legato al fuoco, al sangue e alla passione.": "Червоний — видимий колір із найбільшою довжиною хвилі, і він одним із перших привертає погляд. Його пов'язують із вогнем, кров'ю та пристрастю.",
  "Nella cultura occidentale viene associato a energia, urgenza e desiderio, ed è il colore più usato per segnalare pericoli e divieti.": "У західній культурі його асоціюють з енергією, терміновістю та бажанням, і саме його найчастіше використовують для позначення небезпеки й заборон.",
  "Nel design si usa con misura, per avvisi, saldi e pulsanti importanti, perché in grandi quantità può risultare aggressivo.": "У дизайні його використовують помірно — для попереджень, розпродажів і важливих кнопок, бо у великій кількості він може здаватися агресивним.",
  "Molte catene di fast food hanno il rosso nel logo: è un colore che si nota subito e che viene spesso associato al cibo e all'energia.": "Багато мереж фастфуду мають червоний колір у логотипі: його одразу помічають і часто асоціюють із їжею та енергією.",
  "Il significato del giallo": "Значення жовтого",
  "Tra i colori puri, il giallo è quello che appare più luminoso: richiama il sole, la luce e l'estate e cattura facilmente lo sguardo.": "Серед чистих кольорів жовтий здається найяскравішим: він нагадує про сонце, світло й літо та легко привертає погляд.",
  "Viene associato all'ottimismo, alla creatività e alla curiosità; usato su grandi superfici, però, può risultare abbagliante e stancare la vista.": "Його асоціюють з оптимізмом, креативністю та допитливістю; проте на великих поверхнях він може сліпити й втомлювати зір.",
  "Abbinato al nero crea un contrasto molto forte, leggibile anche a distanza: per questo è usato nella segnaletica e negli avvisi di pericolo.": "У поєднанні з чорним він створює дуже сильний контраст, який добре видно навіть здалеку, тому його використовують у дорожніх знаках і попередженнях про небезпеку.",
  "Dal 1967 i taxi autorizzati di New York devono essere gialli: un colore che si riconosce subito, anche nel traffico.": "З 1967 року ліцензовані таксі Нью-Йорка мають бути жовтими: цей колір одразу впізнають навіть у транспортному потоці.",
  "Il significato del verde": "Значення зеленого",
  "Il verde è il colore della natura, della crescita e del rinnovamento. L'occhio umano è particolarmente sensibile alla luce verde-gialla, che percepisce come molto luminosa.": "Зелений — колір природи, зростання й оновлення. Людське око особливо чутливе до жовто-зеленого світла і сприймає його як дуже яскраве.",
  "Viene associato a equilibrio, salute e tranquillità ed è considerato un colore riposante.": "Його асоціюють із рівновагою, здоров'ям і спокоєм та вважають кольором, що дає відпочинок очам.",
  "Nel design indica spesso qualcosa di positivo o permesso, come un'operazione riuscita o un semaforo che dà il via libera.": "У дизайні він часто позначає щось позитивне чи дозволене — наприклад, успішну операцію або сигнал світлофора, що дозволяє рух.",
  "In Europa i cartelli delle uscite di emergenza sono verdi, perché il verde indica sicurezza e “via libera”. Negli Stati Uniti, invece, le scritte EXIT sono spesso rosse.": "У Європі знаки евакуаційних виходів зелені, бо зелений означає безпеку та «вільний шлях». А от у США написи EXIT часто червоні.",
  "Il significato del bianco": "Значення білого",
  "La luce bianca contiene tutti i colori dello spettro visibile, come mostra un prisma. Nella cultura occidentale il bianco rappresenta purezza, pulizia e nuovi inizi.": "Біле світло містить усі кольори видимого спектра, що можна побачити за допомогою призми. У західній культурі білий символізує чистоту, охайність і новий початок.",
  "Nel design è fondamentale come spazio vuoto: dà respiro ai contenuti e comunica ordine, semplicità ed eleganza.": "У дизайні він важливий як порожній простір: дає вмісту «дихати» та передає порядок, простоту й елегантність.",
  "Il suo significato cambia con la cultura: in diversi paesi asiatici, come Cina, Giappone e India, il bianco è tradizionalmente il colore del lutto.": "Його значення залежить від культури: у низці азійських країн, як-от Китай, Японія та Індія, білий традиційно є кольором жалоби.",
  "Molti marchi di tecnologia usano grandi spazi bianchi nei negozi e nelle confezioni per comunicare semplicità e qualità.": "Багато технологічних брендів використовують багато білого простору в магазинах і на упаковці, щоб передати простоту та якість.",
  "Il significato del nero": "Значення чорного",
  "Il nero corrisponde all'assenza di luce. Viene associato a forza, eleganza e mistero, ma anche a serietà e, in molte culture occidentali, al lutto.": "Чорний відповідає відсутності світла. Його асоціюють із силою, елегантністю й таємничістю, а також із серйозністю та, у багатьох західних культурах, із жалобою.",
  "Nella moda e nel lusso è il colore della raffinatezza: fa apparire gli oggetti più preziosi e senza tempo.": "У моді та сегменті розкоші це колір вишуканості: завдяки йому речі здаються ціннішими й позачасовими.",
  "Nel design dà contrasto e peso: il testo nero su fondo bianco ha il contrasto massimo possibile (21:1) ed è tra le combinazioni più leggibili.": "У дизайні він додає контрасту й ваги: чорний текст на білому тлі має максимально можливий контраст (21:1) і належить до найчитабельніших поєднань.",
  "Nel 1926 la rivista Vogue presentò il “piccolo abito nero” di Coco Chanel come un capo adatto a tutte le donne: un colore legato al lutto diventò un simbolo di eleganza.": "У 1926 році журнал Vogue представив «маленьку чорну сукню» Коко Шанель як річ, що пасує кожній жінці: колір, пов'язаний із жалобою, став символом елегантності.",
  "RGB: i colori della luce": "RGB: кольори світла",
  "Gli schermi creano i colori con la luce: ogni pixel è formato da tre piccole luci, rossa (Red), verde (Green) e blu (Blue). Per questo il modello si chiama RGB.": "Екрани створюють кольори за допомогою світла: кожен піксель складається з трьох маленьких джерел світла — червоного (Red), зеленого (Green) і синього (Blue). Тому модель називається RGB.",
  "È un modello additivo: più luce aggiungi, più il colore si schiarisce. Rosso e verde danno il giallo, verde e blu il ciano, rosso e blu il magenta; tutte e tre al massimo danno il bianco.": "Це адитивна модель: що більше світла додаєш, то світлішим стає колір. Червоний і зелений дають жовтий, зелений і синій — ціан, червоний і синій — мадженту; усі три на максимумі дають білий.",
  "Ogni canale va da 0 a 255: rgb(255, 0, 0) è il rosso puro, rgb(0, 0, 0) il nero e rgb(255, 255, 255) il bianco. In tutto si ottengono più di 16 milioni di colori.": "Кожен канал має значення від 0 до 255: rgb(255, 0, 0) — чистий червоний, rgb(0, 0, 0) — чорний, rgb(255, 255, 255) — білий. Загалом виходить понад 16 мільйонів кольорів.",
  "Se guardi uno schermo con una lente d'ingrandimento vedi i piccoli punti rossi, verdi e blu che, da lontano, l'occhio fonde in un unico colore.": "Якщо подивитися на екран крізь лупу, видно дрібні червоні, зелені й сині точки, які здалеку око зливає в один колір.",
  "Il codice HEX": "Код HEX",
  "Il codice HEX è un modo compatto di scrivere un colore RGB: un cancelletto seguito da sei caratteri, come #FF7A00.": "Код HEX — це компактний спосіб записати колір RGB: знак # і шість символів, наприклад #FF7A00.",
  "I sei caratteri sono tre coppie: la prima indica il rosso, la seconda il verde, la terza il blu. Ogni coppia va da 00 (niente) a FF (massimo), cioè da 0 a 255 in numerazione esadecimale.": "Шість символів утворюють три пари: перша означає червоний, друга — зелений, третя — синій. Кожна пара має значення від 00 (нічого) до FF (максимум), тобто від 0 до 255 у шістнадцятковій системі.",
  "È il formato più usato nel web e nel design: basta copiarlo per avere esattamente lo stesso colore in un sito, in Figma o in un'app.": "Це найпоширеніший формат у вебі та дизайні: достатньо скопіювати код, щоб отримати точно той самий колір на сайті, у Figma чи в застосунку.",
  "Il sistema esadecimale usa 16 simboli: le cifre da 0 a 9 e le lettere da A a F. Così FF vale 15 × 16 + 15 = 255.": "Шістнадцяткова система використовує 16 символів: цифри від 0 до 9 і літери від A до F. Тому FF = 15 × 16 + 15 = 255.",
  "Tinta, saturazione e luminosità": "Відтінок, насиченість і світлота",
  "Il modello HSL descrive i colori in un modo vicino a come li descriviamo a parole. La tinta (Hue) è la posizione sulla ruota cromatica, da 0° a 360°: il rosso è a 0°, il verde a 120°, il blu a 240°.": "Модель HSL описує кольори приблизно так, як ми описуємо їх словами. Відтінок (Hue) — це положення на колірному колі від 0° до 360°: червоний — на 0°, зелений — на 120°, синій — на 240°.",
  "La saturazione dice quanto il colore è intenso: al 100% è vivo, allo 0% diventa grigio. La luminosità va dal nero (0%) al bianco (100%), con il colore pieno al 50%.": "Насиченість показує, наскільки колір інтенсивний: на 100% він яскравий, на 0% стає сірим. Світлота змінюється від чорного (0%) до білого (100%), а чистий колір — на 50%.",
  "HSL è comodo per creare palette: tenendo ferma la tinta e cambiando saturazione e luminosità ottieni tante sfumature armoniche dello stesso colore.": "HSL зручна для створення палітр: якщо залишити відтінок незмінним і змінювати насиченість і світлоту, отримаєш багато гармонійних відтінків одного кольору.",
  "Le armonie si calcolano sulla tinta: il complementare è a 180°, una triade a 120°. Attenzione: sulla ruota digitale (RGB e HSL) il complementare del blu è il giallo, mentre sulla ruota tradizionale dei pittori (rosso, giallo, blu), usata nelle lezioni sulle combinazioni, è l'arancione.": "Гармонії розраховують за відтінком: додатковий колір розташований на відстані 180°, тріада — через 120°. Увага: на цифровому колі (RGB і HSL) додатковим до синього є жовтий, а на традиційному колі художників (червоний, жовтий, синій), яке використовується в уроках про поєднання, — помаранчевий.",
  "RGB e CMYK: schermo e stampa": "RGB і CMYK: екран і друк",
  "Le stampanti non usano la luce ma gli inchiostri: ciano (Cyan), magenta, giallo (Yellow) e nero (Key). È il modello CMYK.": "Принтери використовують не світло, а фарби: блакитну (Cyan), пурпурову (Magenta), жовту (Yellow) і чорну (Key). Це модель CMYK.",
  "È un modello sottrattivo: ogni inchiostro assorbe una parte della luce, quindi più inchiostro aggiungi, più il colore si scurisce. Il nero si aggiunge a parte perché mescolando ciano, magenta e giallo si ottiene un marrone scuro, non un nero pieno.": "Це субтрактивна модель: кожна фарба поглинає частину світла, тож що більше фарби, то темніший колір. Чорну додають окремо, бо суміш блакитної, пурпурової та жовтої дає темно-коричневий, а не глибокий чорний.",
  "Alcuni colori molto accesi dello schermo non si possono stampare: per questo un colore può apparire più spento su carta che sul monitor, e chi progetta per la stampa controlla i colori in CMYK già durante il lavoro.": "Деякі дуже яскраві кольори екрана неможливо надрукувати, тому на папері колір може виглядати тьмянішим, ніж на моніторі. Саме тому дизайнери друкованої продукції перевіряють кольори в CMYK уже під час роботи.",
  "La K di CMYK viene da Key plate, la lastra “chiave” che nella stampa tipografica portava i dettagli in nero.": "Літера K у CMYK походить від Key plate — «ключової» друкарської форми, яка в поліграфії переносила чорні деталі.",
  "Contrasto e accessibilità": "Контраст і доступність",
  "Un testo è leggibile quando c'è abbastanza differenza di luminosità tra testo e sfondo. Questa differenza si misura con il rapporto di contrasto, da 1:1 (nessuna differenza) a 21:1 (nero su bianco).": "Текст добре читається, коли між ним і тлом є достатня різниця яскравості. Її вимірюють коефіцієнтом контрасту — від 1:1 (різниці немає) до 21:1 (чорне на білому).",
  "Le linee guida internazionali WCAG chiedono almeno 4,5:1 per il testo normale e 3:1 per i testi grandi e le icone: è il livello AA. Il livello AAA chiede 7:1.": "Міжнародні настанови WCAG вимагають щонайменше 4,5:1 для звичайного тексту та 3:1 для великого тексту й іконок — це рівень AA. Рівень AAA вимагає 7:1.",
  "Circa l'8% degli uomini e lo 0,5% delle donne di origine europea ha una forma di daltonismo: per questo non bisogna affidare un'informazione solo al colore, ma aggiungere anche testo, icone o forme.": "Приблизно 8% чоловіків і 0,5% жінок європейського походження мають певну форму дальтонізму, тому не варто передавати інформацію лише кольором — додавай також текст, іконки чи форми.",
  "Anche CHROMA controlla il contrasto: quando scegli un tema, l'app corregge da sola i colori perché testi e pulsanti restino leggibili.": "CHROMA теж перевіряє контраст: коли ти обираєш тему, застосунок сам коригує кольори, щоб текст і кнопки залишалися читабельними.",
  "Complementari": "Додаткові",
  "I colori complementari sono posizionati uno di fronte all'altro nella ruota cromatica. Creano il contrasto di tinta più forte e attirano subito l'attenzione.": "Додаткові кольори розташовані один навпроти одного на колірному колі. Вони створюють найсильніший контраст відтінків і одразу привертають увагу.",
  "La combinazione utilizza due colori opposti. Sulla ruota tradizionale dei pittori (rosso, giallo, blu) le coppie sono blu e arancione, rosso e verde, giallo e viola.": "Це поєднання двох протилежних кольорів. На традиційному колі художників (червоний, жовтий, синій) такі пари — синій і помаранчевий, червоний і зелений, жовтий і фіолетовий.",
  "Ideale per evidenziare elementi importanti, creare energia visiva e ottenere composizioni dinamiche. Esempi: Blu + Arancione, Rosso + Verde, Viola + Giallo.": "Ідеально, щоб виділити важливі елементи, додати візуальної енергії та створити динамічну композицію. Приклади: синій + помаранчевий, червоний + зелений, фіолетовий + жовтий.",
  "Questa combinazione è molto utilizzata nel cinema, nella pubblicità e nel design per evidenziare elementi importanti. Alcuni esempi famosi sono il blu con l'arancione oppure il rosso con il verde.": "Це поєднання часто використовують у кіно, рекламі та дизайні, щоб виділити важливе. Відомі приклади — синій із помаранчевим або червоний із зеленим.",
  "I colori complementari possono essere usati per creare immagini energiche e dinamiche, ma devono essere bilanciati per evitare un effetto troppo aggressivo.": "Додаткові кольори допомагають створювати енергійні й динамічні зображення, але їх треба врівноважувати, щоб ефект не був надто агресивним.",
  "Analoghi": "Аналогові",
  "I colori analoghi sono colori vicini tra loro sulla ruota cromatica. Generano armonia e continuità visiva.": "Аналогові кольори розташовані поруч на колірному колі. Вони створюють гармонію та візуальну цілісність.",
  "Si scelgono generalmente tre colori adiacenti che condividono caratteristiche simili.": "Зазвичай обирають три сусідні кольори зі схожими характеристиками.",
  "Perfetta per creare ambienti rilassanti, design equilibrati e palette naturali. Esempi: Blu + Blu-verde + Verde, Rosso + Rosso-arancio + Arancione.": "Ідеально для спокійної атмосфери, урівноваженого дизайну та природних палітр. Приклади: синій + синьо-зелений + зелений, червоний + червоно-помаранчевий + помаранчевий.",
  "Questa combinazione è molto utilizzata per paesaggi, interfacce rilassanti e composizioni che devono trasmettere equilibrio.": "Це поєднання часто використовують для пейзажів, спокійних інтерфейсів і композицій, що мають передавати рівновагу.",
  "Poiché il contrasto è limitato, i colori analoghi aiutano a creare una sensazione di continuità e fluidità visiva.": "Оскільки контраст обмежений, аналогові кольори допомагають створити відчуття цілісності та плавності.",
  "Triade": "Тріада",
  "La combinazione triadica utilizza tre colori equidistanti sulla ruota cromatica.": "Тріадне поєднання використовує три кольори, рівновіддалені на колірному колі.",
  "I colori formano un triangolo equilatero e mantengono un buon equilibrio tra contrasto e armonia.": "Кольори утворюють рівносторонній трикутник і зберігають добрий баланс між контрастом і гармонією.",
  "Ottima per progetti creativi, illustrazioni e interfacce vivaci ma bilanciate. Esempi: Rosso + Giallo + Blu.": "Чудово підходить для творчих проєктів, ілюстрацій і яскравих, але врівноважених інтерфейсів. Приклад: червоний + жовтий + синій.",
  "Questo schema crea palette vivaci e bilanciate, mantenendo un buon equilibrio tra contrasto e armonia.": "Ця схема дає яскраві й урівноважені палітри з добрим балансом контрасту та гармонії.",
  "Molti loghi e illustrazioni utilizzano combinazioni triadiche per ottenere design accattivanti senza risultare disordinati.": "Багато логотипів та ілюстрацій використовують тріади, щоб бути помітними, але не хаотичними.",
  "Split complementari": "Розщеплені додаткові",
  "Questa combinazione parte da un colore principale e utilizza i due colori adiacenti al suo complementare.": "Це поєднання починається з основного кольору й використовує два кольори, сусідні з його додатковим.",
  "Offre un contrasto elevato ma meno aggressivo rispetto ai complementari diretti.": "Воно дає високий контраст, але м'якший, ніж прямі додаткові кольори.",
  "Ideale per chi desidera creare tensione visiva mantenendo una maggiore armonia. Esempi: Blu con Giallo-Arancio e Rosso-Arancio.": "Ідеально, якщо хочеш створити візуальну напругу, зберігши більше гармонії. Приклад: синій із жовто-помаранчевим і червоно-помаранчевим.",
  "Questo sistema mantiene un forte contrasto ma risulta più equilibrato rispetto ai complementari diretti.": "Ця схема зберігає сильний контраст, але виглядає врівноваженіше, ніж прямі додаткові кольори.",
  "È molto apprezzato nel design perché offre varietà cromatica senza creare tensioni visive eccessive.": "Її цінують у дизайні, бо вона дає колірне розмаїття без надмірної візуальної напруги.",
  "Rettangolo": "Прямокутник",
  "La combinazione rettangolare utilizza quattro colori organizzati in due coppie complementari.": "Прямокутне поєднання використовує чотири кольори, що утворюють дві пари додаткових.",
  "I colori formano un rettangolo sulla ruota cromatica, offrendo una palette ricca e versatile.": "На колірному колі кольори утворюють прямокутник і дають багату та універсальну палітру.",
  "Perfetta per progetti complessi che richiedono varietà cromatica mantenendo equilibrio. Esempi: Blu, Verde, Arancione e Rosso.": "Ідеально для складних проєктів, яким потрібне колірне розмаїття без втрати рівноваги. Приклад: синій, зелений, помаранчевий і червоний.",
  "Questo schema offre molta varietà cromatica e permette di creare composizioni ricche e dinamiche.": "Ця схема дає багато колірного розмаїття й дозволяє створювати насичені та динамічні композиції.",
  "Per ottenere un buon risultato è consigliabile scegliere un colore dominante e usare gli altri come supporto.": "Для доброго результату варто обрати один домінантний колір, а інші використовувати як допоміжні.",
  "Quadrato": "Квадрат",
  "La combinazione quadrata utilizza quattro colori equidistanti tra loro sulla ruota cromatica.": "Квадратне поєднання використовує чотири кольори, рівновіддалені один від одного на колірному колі.",
  "I colori formano un quadrato e distribuiscono uniformemente il contrasto.": "Кольори утворюють квадрат і рівномірно розподіляють контраст.",
  "Ideale per creare design energici, moderni e molto colorati. Esempio sulla ruota tradizionale: Giallo, Rosso-arancio, Viola e Blu-verde.": "Ідеально для енергійного, сучасного й дуже барвистого дизайну. Приклад на традиційному колі: жовтий, червоно-помаранчевий, фіолетовий і синьо-зелений.",
  "Produce palette molto vivaci e dinamiche grazie alla distribuzione uniforme dei colori.": "Завдяки рівномірному розподілу кольорів виходять дуже яскраві й динамічні палітри.",
  "È uno schema ideale per progetti creativi, illustrazioni e design che vogliono trasmettere energia e movimento.": "Це ідеальна схема для творчих проєктів, ілюстрацій і дизайну, що має передавати енергію та рух.",
  "A quali sensazioni viene associato più spesso il blu?": "З якими відчуттями найчастіше асоціюють синій?",
  "A) Calma e fiducia": "A) Спокій і довіра",
  "B) Rabbia e urgenza": "B) Гнів і терміновість",
  "C) Fame ed energia": "C) Голод і енергія",
  "Perché molte aziende tecnologiche usano il blu?": "Чому багато технологічних компаній використовують синій?",
  "A) Perché è economico da stampare": "A) Бо його дешево друкувати",
  "B) Perché viene associato all'affidabilità": "B) Бо його асоціюють із надійністю",
  "C) Perché attira l'attenzione sui saldi": "C) Бо він привертає увагу до знижок",
  "A cosa vengono associate le tonalità scure del blu?": "З чим асоціюють темні відтінки синього?",
  "A) Allegria e gioco": "A) Веселощі й гра",
  "B) Pericolo": "B) Небезпека",
  "C) Autorevolezza ed eleganza": "C) Авторитет і елегантність",
  "Da quali colori nasce l'arancione?": "З яких кольорів утворюється помаранчевий?",
  "A) Rosso e Giallo": "A) Червоний і жовтий",
  "B) Blu e Giallo": "B) Синій і жовтий",
  "C) Rosso e Blu": "C) Червоний і синій",
  "Quale emozione viene associata all'arancione?": "Яку емоцію асоціюють із помаранчевим?",
  "A) Tristezza": "A) Смуток",
  "B) Entusiasmo": "B) Ентузіазм",
  "C) Freddezza": "C) Холодність",
  "Dove viene usato spesso l'arancione nel design?": "Де в дизайні часто використовують помаранчевий?",
  "A) Negli sfondi dei documenti legali": "A) У тлі юридичних документів",
  "B) Nei testi lunghi": "B) У довгих текстах",
  "C) Nei pulsanti di invito all'azione": "C) У кнопках із закликом до дії",
  "Da quali colori nasce il viola?": "З яких кольорів утворюється фіолетовий?",
  "A) Giallo e Blu": "A) Жовтий і синій",
  "B) Rosso e Blu": "B) Червоний і синій",
  "C) Verde e Rosso": "C) Зелений і червоний",
  "A cosa è storicamente associato il viola?": "З чим історично асоціюється фіолетовий?",
  "A) Alla regalità e al lusso": "A) Із царственістю та розкішшю",
  "B) Al lavoro nei campi": "B) Із польовими роботами",
  "C) Alla segnaletica stradale": "C) Із дорожніми знаками",
  "Come vengono percepite spesso le tonalità chiare come il lilla?": "Як часто сприймають світлі відтінки, як-от бузковий?",
  "A) Pericolo": "A) Небезпека",
  "B) Aggressività": "B) Агресивність",
  "C) Delicatezza e romanticismo": "C) Ніжність і романтика",
  "Quali sensazioni vengono associate al rosso?": "Які відчуття асоціюють із червоним?",
  "A) Energia e urgenza": "A) Енергія і терміновість",
  "B) Calma e riposo": "B) Спокій і відпочинок",
  "C) Freddezza": "C) Холодність",
  "Perché il rosso va usato con misura nel design?": "Чому в дизайні червоний слід використовувати помірно?",
  "A) Perché è poco visibile": "A) Бо його погано видно",
  "B) Perché può risultare aggressivo": "B) Бо він може здаватися агресивним",
  "C) Perché non si stampa bene": "C) Бо він погано друкується",
  "Dove si usa spesso il rosso?": "Де часто використовують червоний?",
  "A) Negli sfondi dei testi lunghi": "A) У тлі довгих текстів",
  "B) Nelle app per dormire": "B) У застосунках для сну",
  "C) In avvisi, saldi e pulsanti importanti": "C) У попередженнях, розпродажах і важливих кнопках",
  "A cosa viene associato il giallo?": "З чим асоціюють жовтий?",
  "A) Al lutto": "A) Із жалобою",
  "B) All'ottimismo e alla luce": "B) З оптимізмом і світлом",
  "C) Al silenzio": "C) Із тишею",
  "Con quale colore il giallo è più leggibile a distanza?": "З яким кольором жовтий найкраще видно здалеку?",
  "A) Con il nero": "A) З чорним",
  "B) Con il bianco": "B) З білим",
  "C) Con l'arancione": "C) З помаранчевим",
  "Cosa può succedere usando troppo giallo?": "Що може статися, якщо використати забагато жовтого?",
  "A) Il testo diventa più leggibile": "A) Текст стане читабельнішим",
  "B) Scompare il contrasto con il nero": "B) Зникне контраст із чорним",
  "C) Può abbagliare e stancare la vista": "C) Він може сліпити й втомлювати зір",
  "Quale concetto viene associato al verde?": "Яке поняття асоціюють із зеленим?",
  "A) Pericolo": "A) Небезпека",
  "B) Lusso": "B) Розкіш",
  "C) Natura e crescita": "C) Природа і зростання",
  "Cosa indica il verde nelle interfacce?": "Що позначає зелений в інтерфейсах?",
  "A) Un'operazione riuscita": "A) Успішну операцію",
  "B) Un errore grave": "B) Серйозну помилку",
  "C) Un contenuto vietato": "C) Заборонений вміст",
  "Che effetto viene attribuito al verde?": "Який ефект приписують зеленому?",
  "A) Agitazione": "A) Збудження",
  "B) Equilibrio e riposo": "B) Рівновагу й відпочинок",
  "C) Fame": "C) Голод",
  "Cosa contiene la luce bianca?": "Що містить біле світло?",
  "A) Nessun colore": "A) Жодного кольору",
  "B) Tutti i colori dello spettro visibile": "B) Усі кольори видимого спектра",
  "C) Solo il blu": "C) Лише синій",
  "A cosa serve il bianco nel design?": "Для чого в дизайні потрібен білий?",
  "A) A dare respiro ai contenuti": "A) Щоб дати вмісту «дихати»",
  "B) A nascondere il testo": "B) Щоб приховати текст",
  "C) Ad aumentare il caos": "C) Щоб додати хаосу",
  "In diversi paesi asiatici il bianco rappresenta tradizionalmente…": "У низці азійських країн білий традиційно символізує…",
  "A) La festa": "A) Свято",
  "B) La ricchezza": "B) Багатство",
  "C) Il lutto": "C) Жалобу",
  "Il nero è…": "Чорний — це…",
  "A) L'assenza di luce": "A) Відсутність світла",
  "B) La somma di tutti i colori della luce": "B) Сума всіх кольорів світла",
  "C) Un colore caldo": "C) Теплий колір",
  "In quale settore il nero viene associato alla raffinatezza?": "У якій сфері чорний асоціюють із вишуканістю?",
  "A) Nei giochi per bambini": "A) В іграх для дітей",
  "B) Nella moda e nel lusso": "B) У моді та сегменті розкоші",
  "C) Nella segnaletica stradale": "C) У дорожніх знаках",
  "Quale di queste combinazioni è la più leggibile?": "Яке з цих поєднань найчитабельніше?",
  "A) Giallo su bianco": "A) Жовте на білому",
  "B) Blu su viola": "B) Синє на фіолетовому",
  "C) Testo nero su fondo bianco": "C) Чорний текст на білому тлі",
  "Che cosa significa RGB?": "Що означає RGB?",
  "A) Rosso, Giallo, Blu": "A) Червоний, жовтий, синій",
  "B) Red, Green, Blue: rosso, verde, blu": "B) Red, Green, Blue: червоний, зелений, синій",
  "C) Rosa, Grigio, Bianco": "C) Рожевий, сірий, білий",
  "Cosa ottieni sommando luce rossa e luce verde?": "Що вийде, якщо скласти червоне й зелене світло?",
  "A) Giallo": "A) Жовтий",
  "B) Marrone": "B) Коричневий",
  "C) Viola": "C) Фіолетовий",
  "Quale valore rappresenta il bianco?": "Яке значення відповідає білому?",
  "Quale di questi è un codice HEX valido?": "Який із цих кодів HEX правильний?",
  "Nel codice #FF0000, quale canale è al massimo?": "Який канал у коді #FF0000 має максимальне значення?",
  "A) Il verde": "A) Зелений",
  "B) Il rosso": "B) Червоний",
  "C) Il blu": "C) Синій",
  "Che colore è #000000?": "Який колір має код #000000?",
  "A) Bianco": "A) Білий",
  "B) Grigio": "B) Сірий",
  "C) Nero": "C) Чорний",
  "Cosa indica la tinta (Hue)?": "Що позначає відтінок (Hue)?",
  "A) La posizione del colore sulla ruota": "A) Положення кольору на колі",
  "B) Quanto il colore è chiaro": "B) Наскільки колір світлий",
  "C) Quanto costa stamparlo": "C) Скільки коштує його надрукувати",
  "Un colore con saturazione 0% appare…": "Як виглядає колір із насиченістю 0%?",
  "A) Più vivo": "A) Яскравіший, ніж зазвичай",
  "C) Fluorescente": "C) Флуоресцентний",
  "A quanti gradi di distanza si trova il complementare?": "На скільки градусів віддалений додатковий колір?",
  "Quale modello usano le stampanti?": "Яку модель використовують принтери?",
  "Nel modello sottrattivo, aggiungendo inchiostro il colore diventa…": "У субтрактивній моделі, якщо додати фарби, колір стає…",
  "A) Più chiaro": "A) Світлішим",
  "B) Più scuro": "B) Темнішим",
  "C) Trasparente": "C) Прозорим",
  "Perché un colore acceso può sembrare spento su carta?": "Чому яскравий колір на папері може виглядати тьмяним?",
  "A) Perché la carta è bianca": "A) Бо папір білий",
  "B) Perché lo schermo è rotto": "B) Бо екран зламаний",
  "C) Perché alcuni colori RGB non sono stampabili in CMYK": "C) Бо деякі кольори RGB неможливо надрукувати в CMYK",
  "Qual è il contrasto minimo AA per un testo normale?": "Який мінімальний контраст рівня AA для звичайного тексту?",
  "Quale combinazione ha il contrasto più alto?": "Яке поєднання має найвищий контраст?",
  "A) Nero su bianco": "A) Чорне на білому",
  "B) Giallo su bianco": "B) Жовте на білому",
  "C) Grigio su grigio": "C) Сіре на сірому",
  "Come aiuti chi è daltonico?": "Як допомогти людям із дальтонізмом?",
  "A) Usando solo rosso e verde": "A) Використовувати лише червоний і зелений",
  "B) Usando colori più chiari": "B) Використовувати світліші кольори",
  "C) Affiancando al colore testo, icone o forme": "C) Доповнювати колір текстом, іконками чи формами",
  "Dove si trovano i colori complementari sulla ruota cromatica?": "Де на колірному колі розташовані додаткові кольори?",
  "A) Uno accanto all'altro": "A) Поруч один з одним",
  "B) Uno di fronte all'altro": "B) Один навпроти одного",
  "C) A 90° uno dall'altro": "C) Під кутом 90° один до одного",
  "Quale di queste è una coppia complementare?": "Яка з цих пар — додаткова?",
  "A) Blu e Arancione": "A) Синій і помаранчевий",
  "B) Blu e Azzurro": "B) Синій і блакитний",
  "C) Rosso e Arancione": "C) Червоний і помаранчевий",
  "A cosa bisogna fare attenzione usando i complementari?": "На що зважати, використовуючи додаткові кольори?",
  "A) Sono troppo spenti": "A) Вони надто тьмяні",
  "B) Non si notano": "B) Їх не помітно",
  "C) Vanno bilanciati per non risultare aggressivi": "C) Їх треба врівноважувати, щоб вони не здавалися агресивними",
  "Come sono disposti i colori analoghi?": "Як розташовані аналогові кольори?",
  "A) Vicini tra loro sulla ruota": "A) Поруч на колі",
  "B) Opposti tra loro": "B) Один навпроти одного",
  "C) Ai vertici di un quadrato": "C) У вершинах квадрата",
  "Quale palette è analoga?": "Яка палітра аналогова?",
  "A) Rosso + Verde": "A) Червоний + зелений",
  "B) Blu + Blu-verde + Verde": "B) Синій + синьо-зелений + зелений",
  "C) Giallo + Viola": "C) Жовтий + фіолетовий",
  "Che effetto producono di solito i colori analoghi?": "Який ефект зазвичай створюють аналогові кольори?",
  "A) Tensione e conflitto": "A) Напругу й конфлікт",
  "B) Massimo contrasto": "B) Максимальний контраст",
  "C) Armonia e continuità": "C) Гармонію та цілісність",
  "Quanti colori usa una triade?": "Скільки кольорів у тріаді?",
  "A) Due": "A) Два",
  "B) Tre": "B) Три",
  "C) Quattro": "C) Чотири",
  "Che forma disegnano i colori di una triade sulla ruota?": "Яку фігуру утворюють кольори тріади на колі?",
  "A) Un triangolo": "A) Трикутник",
  "B) Un quadrato": "B) Квадрат",
  "C) Una linea": "C) Лінію",
  "Quale di queste è una triade?": "Що з цього є тріадою?",
  "A) Blu + Blu-verde + Verde": "A) Синій + синьо-зелений + зелений",
  "B) Rosso + Verde": "B) Червоний + зелений",
  "C) Rosso + Giallo + Blu": "C) Червоний + жовтий + синій",
  "Da cosa parte uno schema split complementare?": "З чого складається схема розщеплених додаткових кольорів?",
  "A) Da un colore e dai due vicini al suo complementare": "A) З кольору та двох сусідів його додаткового",
  "B) Da quattro colori equidistanti": "B) З чотирьох рівновіддалених кольорів",
  "C) Da tre colori adiacenti": "C) З трьох сусідніх кольорів",
  "Rispetto ai complementari diretti, il contrasto è…": "Порівняно з прямими додатковими кольорами контраст…",
  "A) Nullo": "A) Відсутній",
  "B) Meno aggressivo": "B) М'якший",
  "C) Più aggressivo": "C) Агресивніший",
  "Quale esempio è split complementare?": "Який приклад відповідає розщепленим додатковим?",
  "A) Rosso + Verde": "A) Червоний + зелений",
  "B) Blu + Azzurro": "B) Синій + блакитний",
  "C) Blu con Giallo-Arancio e Rosso-Arancio": "C) Синій із жовто-помаранчевим і червоно-помаранчевим",
  "Come sono organizzati i quattro colori del rettangolo?": "Як організовано чотири кольори прямокутника?",
  "A) In due coppie complementari": "A) У дві пари додаткових",
  "B) Tutti adiacenti": "B) Усі поруч",
  "C) In un triangolo": "C) У трикутник",
  "Qual è un buon consiglio per usare questo schema?": "Яка добра порада для цієї схеми?",
  "A) Usare tutti i colori in parti uguali": "A) Використовувати всі кольори порівну",
  "B) Scegliere un colore dominante": "B) Обрати домінантний колір",
  "C) Evitare i colori caldi": "C) Уникати теплих кольорів",
  "Per quali progetti è adatto il rettangolo?": "Для яких проєктів підходить прямокутник?",
  "A) Solo per il bianco e nero": "A) Лише для чорно-білих",
  "B) Per palette monocromatiche": "B) Для монохромних палітр",
  "C) Per progetti complessi con molta varietà": "C) Для складних проєктів із багатьма кольорами",
  "Come sono disposti i colori del quadrato?": "Як розташовані кольори квадрата?",
  "A) Equidistanti tra loro": "A) На однаковій відстані один від одного",
  "B) Tutti vicini": "B) Усі поруч",
  "C) Solo due opposti": "C) Лише два протилежні",
  "Quanti colori usa lo schema quadrato?": "Скільки кольорів у квадратній схемі?",
  "A) Tre": "A) Три",
  "B) Quattro": "B) Чотири",
  "C) Sei": "C) Шість",
  "Che tipo di design produce?": "Який дизайн вона створює?",
  "A) Spento e neutro": "A) Тьмяний і нейтральний",
  "B) Monocromatico": "B) Монохромний",
  "C) Energico e molto colorato": "C) Енергійний і дуже барвистий"
};
